#!/usr/bin/env python3
"""Build the current fastPLS 0.99.39 manuscript and supplement.

The builder accepts only the current-release tables and figures generated by
build_current_09939_figures.R.  ImageNet is included only when the current
0.99.39 result and figure exist, preventing accidental reuse of older hybrid
runs.
"""

from __future__ import annotations

import csv
import math
import os
from pathlib import Path

from docx import Document
from docx.enum.section import WD_ORIENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


EXTRA = Path(__file__).resolve().parents[1]
PKG = Path(os.environ.get("FASTPLS_SOURCE_ROOT", EXTRA.parent / "fastPLS"))
if "FASTPLS_MANUSCRIPT_OUTPUT" not in os.environ:
    raise RuntimeError("Set FASTPLS_MANUSCRIPT_OUTPUT outside the Git checkouts")
BASE = Path(os.environ["FASTPLS_MANUSCRIPT_OUTPUT"])
FIG = BASE / "figures"
TAB = BASE / "tables"
OUT = BASE / "documents"
OUT.mkdir(parents=True, exist_ok=True)


def rows(name: str) -> list[dict[str, str]]:
    path = TAB / name
    if not path.exists():
        raise FileNotFoundError(f"Missing current evidence: {path}")
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def number(value: str | float | int | None) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return math.nan


def fmt(value: str | float | int | None, digits: int = 3) -> str:
    val = number(value)
    if not math.isfinite(val):
        return "NA"
    return f"{val:.{digits}f}"


def add_line_numbers(section) -> None:
    sect_pr = section._sectPr
    old = sect_pr.find(qn("w:lnNumType"))
    if old is not None:
        sect_pr.remove(old)
    node = OxmlElement("w:lnNumType")
    node.set(qn("w:countBy"), "1")
    node.set(qn("w:restart"), "continuous")
    node.set(qn("w:distance"), "360")
    sect_pr.append(node)


def configure(doc: Document, supplement: bool = False) -> None:
    section = doc.sections[0]
    section.orientation = WD_ORIENT.PORTRAIT
    section.page_width = Inches(8.27)
    section.page_height = Inches(11.69)
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.75 if supplement else 0.85)
    section.right_margin = Inches(0.65 if supplement else 0.75)
    add_line_numbers(section)

    normal = doc.styles["Normal"]
    normal.font.name = "Arial"
    normal.font.size = Pt(9.5 if supplement else 10)
    normal.font.color.rgb = RGBColor(0, 0, 0)
    normal.paragraph_format.space_after = Pt(3)
    normal.paragraph_format.line_spacing = 1.08
    for name, size in (("Title", 17), ("Heading 1", 13), ("Heading 2", 11)):
        style = doc.styles[name]
        style.font.name = "Arial"
        style.font.size = Pt(size)
        style.font.bold = True
        style.font.color.rgb = RGBColor(0, 0, 0)


def set_cell_shading(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shading = tc_pr.find(qn("w:shd"))
    if shading is None:
        shading = OxmlElement("w:shd")
        tc_pr.append(shading)
    shading.set(qn("w:fill"), fill)


def set_cell_margins(cell, top: int = 55, start: int = 65,
                     bottom: int = 55, end: int = 65) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    margins = tc_pr.first_child_found_in("w:tcMar")
    if margins is None:
        margins = OxmlElement("w:tcMar")
        tc_pr.append(margins)
    for name, value in (("top", top), ("start", start),
                        ("bottom", bottom), ("end", end)):
        node = margins.find(qn(f"w:{name}"))
        if node is None:
            node = OxmlElement(f"w:{name}")
            margins.append(node)
        node.set(qn("w:w"), str(value))
        node.set(qn("w:type"), "dxa")


def keep_table_row_together(row, repeat_header: bool = False) -> None:
    tr_pr = row._tr.get_or_add_trPr()
    cant_split = OxmlElement("w:cantSplit")
    tr_pr.append(cant_split)
    if repeat_header:
        header = OxmlElement("w:tblHeader")
        header.set(qn("w:val"), "true")
        tr_pr.append(header)


def paragraph(doc: Document, text: str, bold_prefix: str | None = None):
    par = doc.add_paragraph()
    if bold_prefix and text.startswith(bold_prefix):
        par.add_run(bold_prefix).bold = True
        par.add_run(text[len(bold_prefix):])
    else:
        par.add_run(text)
    return par


def heading(doc: Document, text: str, level: int = 1):
    return doc.add_heading(text, level=level)


def add_table(doc: Document, caption: str, headers: list[str], body: list[list[str]],
              font_size: float = 7.2) -> None:
    cap = doc.add_paragraph()
    cap.add_run(caption).bold = True
    cap.paragraph_format.keep_with_next = True
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    for j, value in enumerate(headers):
        table.rows[0].cells[j].text = value
    for values in body:
        cells = table.add_row().cells
        for j, value in enumerate(values):
            cells[j].text = str(value)
    keep_table_row_together(table.rows[0], repeat_header=True)
    for i, row in enumerate(table.rows):
        if i > 0:
            keep_table_row_together(row)
        for cell in row.cells:
            cell.vertical_alignment = 1
            set_cell_margins(cell)
            if i == 0:
                set_cell_shading(cell, "D9E2F3")
            elif i % 2 == 0:
                set_cell_shading(cell, "F6F8FA")
            for par in cell.paragraphs:
                par.paragraph_format.space_after = Pt(0)
                par.paragraph_format.line_spacing = 1.0
                for run in par.runs:
                    run.font.name = "Arial"
                    run.font.size = Pt(font_size)
                    if i == 0:
                        run.bold = True


def add_figure(doc: Document, filename: str, caption: str, width: float) -> None:
    path = FIG / filename
    if not path.exists():
        raise FileNotFoundError(f"Missing current figure: {path}")
    par = doc.add_paragraph()
    par.alignment = WD_ALIGN_PARAGRAPH.CENTER
    par.paragraph_format.keep_with_next = True
    par.add_run().add_picture(str(path), width=Inches(width))
    cap = doc.add_paragraph()
    cap.add_run(caption).italic = True


def set_core_properties(doc: Document, title: str, subject: str) -> None:
    props = doc.core_properties
    props.title = title
    props.subject = subject
    props.author = "Dupe Ojo; Alessia Vignoli; Stefano Cacciatore; Leonardo Tenori"
    props.keywords = "partial least squares; SIMPLS; randomized SVD; CUDA; Metal; NMR"


fig1 = rows("figure1_independent_implementation_data.csv")
fig2 = rows("figure2_backend_runtime_ratios.csv")
fig3 = rows("figure3_nmr_fixed165_summary.csv")
nmr_path = rows("supplement_nmr_component_path.csv")
nmr_decision = rows("supplement_nmr_component_decision.csv")
component_selection = rows("component_selection.csv")
component_correlations = rows("component_metric_correlations.csv")
multicore = rows("multicore_scaling_summary.csv")
exact_validation = rows("simpls_exact_reference_case_summary.csv")
rsvd_validation = rows("rsvd_qualification_summary.csv")
family_validation = rows("opls_kernel_estimator_validation_summary.csv")
ablation = rows("simpls_multidataset_ablation_effects.csv")

fast = [r for r in fig1 if r["display"].startswith("fastPLS") and math.isfinite(number(r["time_sec"]))]
datasets = sorted({r["dataset"] for r in fast})
fastest_or_tied = 0
workflow_speedups = {}
for dataset in datasets:
    ftime = min(number(r["time_sec"]) for r in fast if r["dataset"] == dataset)
    external = [number(r["time_sec"]) for r in fig1
                if r["dataset"] == dataset
                and not r["display"].startswith(("fastPLS", "IKPLS"))
                and math.isfinite(number(r["time_sec"]))]
    if external and ftime <= min(external) * 1.000001:
        fastest_or_tied += 1
    if external:
        workflow_speedups[dataset] = min(external) / ftime

nmr = {r["implementation"]: r for r in fig3}
decision = {r["family"]: r for r in nmr_decision}
cuda_faster = sum(number(r["ratio"]) > 1 for r in fig2 if r["platform"] == "CUDA")
metal_faster = sum(number(r["ratio"]) > 1 for r in fig2 if r["platform"] == "Metal")
cuda_lower_host_increment = sum(number(r["memory_ratio"]) < 1 for r in fig2
                                if r["platform"] == "CUDA")
metal_lower_host_increment = sum(number(r["memory_ratio"]) < 1 for r in fig2
                                 if r["platform"] == "Metal")

image_table = TAB / "figure4_imagenet_current.csv"
image_figure = FIG / "figure4_imagenet_current.png"
has_imagenet = image_table.exists() and image_figure.exists()
image = rows("figure4_imagenet_current.csv") if has_imagenet else []


title = "fastPLS: accelerated SIMPLS for high-dimensional biomedical data with optional CUDA and Metal routes"
main = Document()
configure(main)
set_core_properties(main, title, "Manuscript for Computer Methods and Programs in Biomedicine")
main.add_heading(title, 0)
paragraph(main, "Dupe Ojo¹*, Alessia Vignoli²*, Stefano Cacciatore¹†, Leonardo Tenori²˒³†")
paragraph(main, "¹ Bioinformatics Unit, International Centre for Genetic Engineering and Biotechnology, Cape Town, South Africa. ² Department of Experimental and Clinical Medicine, University of Florence, Florence, Italy. ³ Magnetic Resonance Center, University of Florence, Florence, Italy.")
paragraph(main, "* Equal contributions. † Co-corresponding authors: Stefano Cacciatore (stefano.cacciatore@icgeb.org) and Leonardo Tenori.")

heading(main, "Abstract")
paragraph(main, "Background and objective: Partial least-squares (PLS) models are valuable for biomedical data with correlated predictors and multivariate responses, but repeated component extraction and dense prediction paths can become computationally limiting. We developed fastPLS around an accelerated execution of the sequential SIMPLS algorithm.")
paragraph(main, "Methods: fastPLS combines compiled component updates, reusable deflation products, compact latent prediction, label-aware classification products and randomized singular value decomposition (rSVD). The package also implements PLS-SVD, orthogonal PLS and kernel PLS, with compiled CPU and optional NVIDIA CUDA and Apple Metal routes. Standard R matrices use float64; float-package inputs select supported float32 routes. Accuracy and timing were evaluated on fixed high-dimensional classification tasks, while a multivariate nuclear magnetic resonance (NMR) application mapped 13,000 predictors to 28,355 response intensities.")
paragraph(main, f"Results: In the single-CPU classification comparison, a current fastPLS SIMPLS workflow was fastest or tied with the fastest completed independent R implementation on {fastest_or_tied} of {len(datasets)} datasets, while retaining comparable predictive accuracy. Accelerator benefit depended on workload: CUDA was faster than its paired CPU result in {cuda_faster} of 44 selected family-dataset comparisons and Metal in {metal_faster} of 44. For NMR, training-only one-standard-error selection retained {decision['plssvd']['selected_ncomp']} PLS-SVD and {decision['simpls']['selected_ncomp']} SIMPLS components within the evaluated grids. At a common 165-component workload, CUDA required {fmt(nmr['PLS-SVD / CUDA']['total_time_sec'], 3)} s for PLS-SVD and {fmt(nmr['SIMPLS / CUDA']['total_time_sec'], 3)} s for SIMPLS, compared with {fmt(nmr['Deposited PLS-SVD / CPU']['total_time_sec'], 3)} s for the deposited float64 PLS-SVD workflow.")
paragraph(main, "Conclusions: fastPLS makes high-dimensional sequential PLS workflows accessible through reduced intermediate storage and compiled numerical execution. rSVD is approximate, and CPU or accelerator choice should be guided by matrix dimensions, numerical diagnostics and the required output contract rather than hardware availability alone.")
paragraph(main, "Keywords: partial least squares; SIMPLS; randomized singular value decomposition; GPU computing; NMR; omics")

heading(main, "1. Introduction")
paragraph(main, "Partial least squares (PLS) constructs latent components that maximize predictor-response association and is widely used when biomedical measurements are numerous, collinear or larger in number than the available samples [1]. PLS has supported metabolomic classification and prediction, including analyses of inflammatory metabolic phenotypes in prostate cancer [2]. It can also serve as supervised feature extraction: the latent scores retain response-relevant structure before a downstream classifier or retrieval method is applied.")
paragraph(main, "Several PLS formulations address different computational and statistical settings. PLS-SVD derives directions from a singular value decomposition of the predictor-response cross-covariance, whereas SIMPLS extracts sequential components while preserving a deflation geometry in the original variable space [3]. Orthogonal PLS separates response-orthogonal variation [4], and kernel PLS permits nonlinear relations through a kernel representation [5]. The R package pls provides established implementations [6], while IKPLS supplies NumPy- and JAX-based improved-kernel PLS algorithms for CPU and GPU computation [7].")
paragraph(main, "For large matrices, the dominant directions can be approximated without a complete singular value decomposition. Randomized SVD (rSVD) constructs a low-dimensional range approximation and can replace expensive dense decompositions when the leading subspace is sufficiently separated [8]. Its approximation depends on rank, oversampling, power iterations, conditioning and seed; therefore, computational gains must be interpreted together with numerical diagnostics.")
paragraph(main, "Multivariate spectral prediction provides a demanding biomedical example. The deposited workflow associated with a recent NMR study predicted 28,355 diffusion-edited spectral intensities from 13,000 NOESY bins in 1,200 training spectra [9]. That implementation used PLS-SVD with an iterative Lanczos bidiagonalization solver and 165 components on its original workstation. The response dimension makes both fitting and prediction expensive, motivating a sequential SIMPLS implementation that approaches one-shot PLS-SVD execution while retaining the ability to construct many components.")
paragraph(main, "Large embedding matrices create a related computational regime after feature extraction. Foundation models such as UNI and Prov-GigaPath produce dense representations for downstream computational pathology analyses [13,14]. We therefore include DINOv2 embeddings [10] derived from ImageNet [16] as an engineering stress test of million-sample matrix processing, not as evidence of biomedical predictive validity.")
paragraph(main, "We present fastPLS, a Bioconductor R package centred on accelerated SIMPLS execution. Its contribution is not the component-path concept already available in conventional SIMPLS software, but the combination of compiled sequential updates, reusable products and workspaces, compact prediction, label-aware class products, matrix-free operators and matched CPU, CUDA and Metal implementations. PLS-SVD, OPLS, kernel PLS, argmax decoding, latent-space linear discriminant analysis (LDA) and compiled cross-validation share the same public interface.")

heading(main, "2. Materials and methods")
heading(main, "2.1 PLS algorithms and numerical execution", 2)
paragraph(main, "Let X be an n by p centred predictor matrix and Y an n by q centred response matrix. The cross-covariance is S = XᵀY. An explicit route materializes S; an implicit route applies SΩ = Xᵀ(YΩ) and SᵀQ = Yᵀ(XQ) without retaining the p by q matrix. The implicit route reduces storage when p q is large, but repeated passes through X and Y can be slower when S fits comfortably in memory.")
paragraph(main, "PLS-SVD approximates S once as UDVᵀ. Scores T = XU and their Gram matrix TᵀT are reused across requested component prefixes, and held-out predictions are formed through latent factors instead of a dense coefficient cube. The attainable number of components is limited by the numerical rank of S and therefore by the response rank.")
paragraph(main, "SIMPLS follows de Jong's sequential orthogonalization and deflation geometry [3]. fastPLS keeps score, loading and deflation workspaces, computes each deflation row once, uses matrix-matrix operations where eligible, updates requested prediction prefixes incrementally and avoids storing fitted responses unless requested. The component-wise route obtains each direction from a fresh randomized sketch of the current deflated cross-covariance. For eligible large multiclass problems, CPU and CUDA routes can instead obtain a small independent candidate block from the current deflated state and consume those candidates sequentially through the SIMPLS orthogonalization and deflation updates. This faster block execution is an approximate SIMPLS variant and is not claimed to reproduce a fresh dominant-direction solve at every component.")

add_table(main, "Algorithm 1. Accelerated SIMPLS execution.", ["Step", "Operation"], [
    ["1", "Centre or scale X with training statistics and centre Y; form S = XᵀY or define its implicit products."],
    ["2", "Initialize empty score, weight, loading and orthogonal-basis workspaces."],
    ["3", "Obtain either one fresh randomized direction or, for an eligible large multiclass problem, an independent candidate block from the current deflated cross-covariance."],
    ["4", "Form and normalize t = Xr; update r against retained scores and weights."],
    ["5", "Compute p = Xᵀt and q = Yᵀt; classification routes may obtain q from class sums without dense one-hot Y."],
    ["6", "Orthogonalize p to obtain v; compute h = vᵀS once; update S ← S − vh; then refresh the direction or continue through the eligible candidate block."],
    ["7", "Append the compact factors and incrementally update only requested fitted or prediction summaries."],
    ["8", "Predict by applying training preprocessing, forming held-out scores XnewR, and mapping them through retained response factors."],
], font_size=7.6)

paragraph(main, "OPLS applies response-orthogonal filtering before fitting the predictive PLS core [4]. Kernel PLS uses a linear shortcut for the linear kernel and an explicitly centred Gram matrix for polynomial and radial-basis kernels [5]. The nonlinear route therefore requires O(n²) storage and is intended for sample sizes whose Gram matrix and working copies fit the available host memory.")

heading(main, "2.2 rSVD, precision and backends", 2)
paragraph(main, "The public low-rank solver is rSVD. Automatic controls use profile-specific oversampling and power iterations: the ordinary profile uses 32 and 5, high-response and sparse-high-class profiles use 48/6 or 64/7, and the massive-cross-covariance SIMPLS profile uses 12/2. The effective controls, seed, executed estimator and numerical status are retained internally for diagnostics. Approximate results are not described as exact equivalence to a dense decomposition.")
paragraph(main, "CPU routes are compiled C++ and call the linked BLAS/LAPACK; multicore execution is available only when the linked numerical library and operation use multiple threads. CUDA routes use NVIDIA cuBLAS, cuSOLVER and cuRAND for device matrix products, factorizations and randomized sketches [11]. Metal float32 routes use Apple Metal Performance Shaders and custom Metal kernels [12]. CUDA PLS-SVD and SIMPLS retain fitting and prediction on the device where supported. Public Metal execution is route-dependent: matrix products and compact prediction use Metal, while component extraction can be hybrid or host-assisted according to the matrix regime; Metal LDA uses the compiled CPU float32 discriminant solver after Metal score projection. OPLS and nonlinear-kernel accelerator routes retain host preprocessing or Gram-matrix stages. Unsupported accelerator or precision combinations return an error rather than silently falling back to CPU.")
paragraph(main, "R stores ordinary numeric matrices in float64. Inputs created with the float package occupy float32 storage and automatically select a supported float32 numerical route. This can reduce the size of input and intermediate arrays, but complete-process memory and runtime also include the R session, loaded data, libraries, allocator state and device context. Precision comparisons consequently report measured memory and prediction differences rather than inferring a twofold process-memory reduction.")

heading(main, "2.3 Classification, regression and validation", 2)
paragraph(main, "For classification, argmax returns the largest predicted dummy-response score. LDA is fitted to retained PLS scores. The pooled within-class covariance is computed as [TᵀT − Σⱼ nⱼμⱼμⱼᵀ]/max(1,n−J), without materializing centred class blocks. Regularized systems are solved by Cholesky factorization and triangular solves. The deterministic scale-normalized fallback tests ρ = 10⁻⁸, 10⁻⁶, 10⁻⁵, 10⁻⁴, 10⁻³ and 10⁻² and uses the first successful factorization. The discriminant is δⱼ(t) = tᵀwⱼ − 0.5 μⱼᵀwⱼ + log(nⱼ/n).")
paragraph(main, "The compiled single and double cross-validation procedures preserve groups supplied through constrain, preventing observations from one subject from entering both training and validation folds. Component number and prediction-relevant model arguments can be selected using accuracy, balanced accuracy, RMSD or Q² as appropriate. Training R², independent-test Q² relative to the training mean and fold-based cross-validated Q² are returned as distinct quantities. Permutation p-values use the finite-sample correction (b + 1)/(B + 1); when groups are supplied, labels are permuted at the exchangeability-block level.")

heading(main, "2.4 Benchmark design and data", 2)
paragraph(main, "The classification comparison used CCLE, CIFAR-100 [15], GTEx v8, MetRef, Retina, Tabula Muris, TCGA-BRCA, TCGA-HNSC methylation and TCGA Pan-Cancer. CBMC CITE-seq and PRISM supplied multivariate regression workloads, and NMR was analysed separately. Dataset construction, preprocessing, dimensions, acquisition and redistribution restrictions are reported in Supplementary Tables S1 and S2. The same prepared train/test split, component count and precision were used within each paired comparison.")
paragraph(main, "The independent-implementation comparison used one effective CPU thread, float32 for current fastPLS rows and the native precision accepted by each independent package. It is therefore an end-to-end workflow comparison rather than an estimator- and precision-identical numerical-kernel comparison. Current fastPLS results are medians of ten isolated processes; independent rows use three or ten isolated processes according to task duration, as recorded in the source table. IKPLS CPU results are shown only where stored matched tasks were available and their differing component counts are marked. Fitting plus held-out prediction was timed, and complete-process resident set size (RSS) was recorded.")
paragraph(main, "The backend comparison evaluated PLS-SVD, SIMPLS, OPLS and kernel PLS on 11 non-NMR datasets using family-specific component counts selected from training data. CPU/CUDA and CPU/Metal ratios are paired within each workstation; values above one favour the accelerator. CUDA timing includes host-to-device transfer, fitting, synchronization, prediction and result transfer. Absolute RSS is a feasibility measure. Incremental RSS subtracts the baseline immediately before fitting, but still measures the complete process; GPU increments may include context and allocator initialization.")
paragraph(main, "CPU thread scaling was evaluated separately with an OpenBLAS-linked build. Three controlled workloads represented sample-rich classification, predictor-wide regression and response-wide regression. One, two and four active OpenBLAS threads were verified directly before each fit, with five repetitions per setting and identical model controls.")
paragraph(main, "The NMR data comprised 1,200 training and 321 held-out spectra with 13,000 predictor bins and 28,355 response intensities. Predictor bins strictly between 4.6 and 4.8 ppm were set to zero in both training and test matrices as routine water-region preprocessing before model selection; response spectra were not masked, and all response columns entered the metrics. Five paired training-only splits were used. For each family, the smallest component count whose mean validation RMSD was no greater than the minimum mean plus its standard error was selected within the evaluated grid. Predictive selection and a separate fixed 165-component implementation comparison were not pooled.")
paragraph(main, "Numerical validation was separated from performance benchmarking. The deterministic component-wise SIMPLS route was compared with a dense reference across conditioned, collinear, rank-deficient, high-response, p<n and p>n cases. Public rSVD profiles were evaluated over repeated seeds on CPU, CUDA and Metal using predefined prediction, correlation, label-agreement and metric tolerances. OPLS and nonlinear kernel PLS were checked independently in deterministic float64 CPU execution. A same-code ablation disabled one optimization at a time to quantify its route-dependent contribution.")
paragraph(main, "Accuracy is the fraction of correct labels; balanced accuracy is the unweighted mean of class-specific recalls. RMSD is the square root of the mean squared response error. Independent-test Q² is 1 minus the prediction sum of squares divided by the sum of squared deviations from the training-response mean. Top-5 accuracy is the fraction for which the observed class is among the five largest predicted class scores. Timing summaries report medians and interquartile ranges where repeated measurements are available.")

heading(main, "3. Results")
heading(main, "3.1 Comparison with independent implementations", 2)
largest_speedups = sorted(workflow_speedups.items(), key=lambda item: item[1], reverse=True)[:3]
speedup_text = "; ".join(f"{dataset}, {value:.2f}-fold" for dataset, value in largest_speedups)
paragraph(main, f"Across the nine classification datasets, the fastest current fastPLS SIMPLS head was faster than or tied with the fastest completed independent R workflow on {fastest_or_tied} datasets (Figure 1). The three largest ratios relative to the fastest completed independent R workflow were {speedup_text}. Predictive accuracy was governed more by the classification head than by runtime: LDA improved several imbalanced or multiclass tasks, whereas argmax remained competitive in image embeddings. Unsupported or unevaluated package-dataset combinations remain marked NE rather than being omitted.")
paragraph(main, "The stored IKPLS CPU comparison was available only for CIFAR-100 at 50 components and MetRef at 22 components, which differ from the training-selected component counts in the main panel. Those rows are therefore shown as context and not used to rank all implementations. The current broad panel does not claim float64 precision matching because several independent packages cannot consume float32 objects and the package workflow outputs differ.")
add_figure(main, "figure1_independent_implementations.png", "Figure 1. Single-CPU SIMPLS classification workflows. Predictive accuracy, total fitting-plus-prediction time and absolute peak process RSS are shown for current fastPLS 0.99.39 and completed independent implementations. NE denotes not evaluated. Current fastPLS values are medians of ten isolated float32 runs; independent rows use three or ten isolated runs in their accepted native precision, as recorded in the source table. IKPLS rows are marked because their stored component counts differ from the training-selected panel.", 6.65)
paragraph(main, "Separate numerical checks supported interpretation of these timing results. The deterministic component-wise SIMPLS route agreed with the dense reference over the evaluated cases, including classification, regression and rank-deficient designs. Each CPU, CUDA and Metal rSVD panel met the predefined numerical tolerances in 174 of 174 comparisons with its current route-specific controls. OPLS and polynomial and radial-basis kernel PLS completed all evaluated deterministic endpoint checks. These checks establish agreement within the evaluated conditions, not universal exactness of randomized routes (Supplementary Table S4). The same-code ablation confirmed that individual execution optimizations can help or hurt according to matrix shape (Supplementary Table S5).")

heading(main, "3.2 CPU and accelerator execution", 2)
paragraph(main, f"Accelerator benefit was conditional on matrix shape and model family (Figure 2). CUDA was faster than the paired CPU run in {cuda_faster} of 44 comparisons, with the clearest gains for larger dense products. Metal was faster in {metal_faster} of 44 comparisons on the 8-GB unified-memory workstation. Incremental host RSS was lower than the paired CPU measurement in {cuda_lower_host_increment} CUDA and {metal_lower_host_increment} Metal comparisons. Small tasks were generally CPU-favourable because device initialization and transfer were comparable with the numerical work. All cells retain the measured ratios; Supplementary Tables S7 and S8 report paired metrics, memory measurements and executed residency so computational differences are not interpreted without numerical context.")
paragraph(main, "Verified four-thread CPU execution produced 1.21-fold, 1.05-fold and 1.79-fold speed-ups for the sample-rich, predictor-wide and response-wide controlled workloads, respectively, with identical predictions across thread counts (Supplementary Table S13 and Figure S13). Thus, a multithreaded build can accelerate matrix-heavy routes, but the sequential SIMPLS updates and workload balance limit scaling.")
add_figure(main, "figure2_backend_runtime.png", "Figure 2. Paired CPU/accelerator runtime and incremental host-memory ratios for all selected family-dataset workloads. Runtime values are CPU time divided by CUDA or Metal time, so values above one favour the accelerator. Memory values are accelerator divided by CPU incremental host RSS, so values below one favour the accelerator. Ratios are paired within each workstation; CUDA and Metal computers are not compared directly. Numerical differences and execution residency are reported in Supplementary Tables S7 and S8.", 6.65)

heading(main, "3.3 Multivariate NMR prediction", 2)
paragraph(main, f"The training-only one-standard-error rule selected {decision['plssvd']['selected_ncomp']} PLS-SVD components and {decision['simpls']['selected_ncomp']} SIMPLS components within grids extending to {decision['simpls']['largest_tested_ncomp']} components (Supplementary Figure S12). The PLS-SVD mean validation minimum occurred at {decision['plssvd']['minimum_mean_ncomp']} components, with {decision['plssvd']['eligible_ncomp']} eligible under the one-standard-error threshold. SIMPLS reached its mean minimum at {decision['simpls']['minimum_mean_ncomp']} components, with {decision['simpls']['eligible_ncomp']} eligible. These values are selections within the evaluated grids rather than unconstrained optima.")
paragraph(main, f"At the common 165-component workload, the deposited float64 PLS-SVD implementation required {fmt(nmr['Deposited PLS-SVD / CPU']['total_time_sec'], 3)} s and {fmt(nmr['Deposited PLS-SVD / CPU']['incremental_rss_mib'], 0)} MiB incremental RSS, with RMSD {fmt(nmr['Deposited PLS-SVD / CPU']['RMSD'], 6)}. Current float32 CUDA PLS-SVD required {fmt(nmr['PLS-SVD / CUDA']['total_time_sec'], 3)} s with RMSD {fmt(nmr['PLS-SVD / CUDA']['RMSD'], 6)}, while CUDA SIMPLS required {fmt(nmr['SIMPLS / CUDA']['total_time_sec'], 3)} s with RMSD {fmt(nmr['SIMPLS / CUDA']['RMSD'], 6)}. Metal PLS-SVD and SIMPLS required {fmt(nmr['PLS-SVD / Metal']['total_time_sec'], 3)} and {fmt(nmr['SIMPLS / Metal']['total_time_sec'], 3)} s, respectively. This fixed-component figure compares feasibility and prediction at the component count used by the deposited workflow; it does not isolate hardware from solver, precision or implementation effects.")
paragraph(main, "The per-spectrum RMSD distribution showed that most held-out spectra clustered near the global error, with a limited upper tail. The displayed spectrum was selected as the held-out sample nearest the median current CPU SIMPLS per-spectrum RMSD. Both the full 12–0 ppm range and the 1.7–0.5 ppm expansion show the agreement of predicted and observed spectral structure. The water interval was removed from predictors only; it remained part of the unmasked response evaluation.")
add_figure(main, "figure3_nmr_fixed165.png", "Figure 3. NMR prediction at a common 165 components. Panels compare fitting-plus-prediction time, held-out RMSD, incremental process RSS, per-spectrum RMSD and observed/predicted spectra for the held-out sample nearest the median current CPU SIMPLS error. The deposited PLS-SVD workflow is a scientific reference implementation, not a hardware- or solver-matched control. All 28,355 response variables contribute to the metrics.", 6.65)

heading(main, "3.4 Foundation-model embedding stress test", 2)
if has_imagenet:
    paragraph(main, "The current 0.99.39 ImageNet/DINOv2 experiment fitted float32 SIMPLS on 1,000,000 training embeddings and evaluated 281,167 held-out embeddings over 100–1,000 requested components with argmax and LDA. Figure 4 reports top-1 and top-5 accuracy, total fitting and prediction time, host RSS and GPU memory. These single-run values are exploratory; the noncanonical split and incomplete extraction provenance preclude a confirmatory predictive claim, and 1,000 components is a boundary stress point rather than an optimum.")
    add_figure(main, "figure4_imagenet_current.png", "Figure 4. Exploratory current-release ImageNet/DINOv2 float32 SIMPLS stress test. Argmax and LDA are evaluated over 100–1,000 components on 1,000,000 training and 281,167 held-out embeddings. Timing includes fitting and held-out prediction. Results are single-run feasibility measurements, not biomedical validation.", 6.65)
else:
    paragraph(main, "A current-release ImageNet/DINOv2 rerun is in progress. No result from an earlier package or hybrid execution path is included in this draft. The final analysis will report argmax and LDA over 100–1,000 components, including fitting, held-out prediction, top-1 and top-5 accuracy, host RSS, GPU memory and route residency.")

heading(main, "4. Discussion")
paragraph(main, "fastPLS accelerates SIMPLS through execution and storage choices rather than redefining the underlying sequential PLS objective. Reusing deflation products and workspaces reduces repeated allocation, while compact latent prediction avoids dense p by q coefficient arrays for every requested prefix. Label-aware products are particularly helpful in multiclass problems because the response cross-product can be formed from class sums without materializing a dense n by J indicator matrix. These gains explain why the current single-CPU workflow was fastest or tied on most completed classification datasets, while the remaining small task showed that package overhead can dominate when all methods finish in hundredths of a second.")
paragraph(main, "The choice between PLS-SVD and SIMPLS depends on the scientific and matrix regime. PLS-SVD obtains a retained subspace in one decomposition and was faster for the extreme-response NMR workload, but its component count is response-rank limited. SIMPLS pays for sequential orthogonalization and deflation, yet can continue beyond a low response rank and supports an interpretable component path. Compact prediction matters most when p, q, the test size or the number of requested prefixes makes dense prediction storage large. Matrix-free cross-covariance is valuable when p q storage is prohibitive; otherwise, materializing S can be faster because it avoids repeated passes through X and Y.")
paragraph(main, "rSVD is retained as the primary solver because it enables the observed large-scale execution, but it is an approximation rather than an exact replacement for every spectrum or conditioning regime. Automatic profiles increase oversampling and power iterations outside the massive-cross-covariance route, and the fit records the effective settings and numerical status. Users conducting confirmatory biomedical analyses should examine stability across seeds and compare predictions or selected components when the singular spectrum is poorly separated. Reaching a component-grid boundary should trigger extension of the training-only grid or cautious reporting as the best tested value.")
paragraph(main, "GPU use is not automatically advantageous. CUDA became useful when dense products or response dimensions were large enough to amortize transfer and context costs; the NMR PLS-SVD result is the clearest example. Most small and moderate tasks remained CPU-favourable. Metal was slower in nearly all selected workloads on the tested 8-GB system, reflecting smaller numerical workloads, unified-memory pressure and a less mature backend. The package therefore errors on unsupported accelerator requests rather than hiding host fallback. OPLS and nonlinear kernel PLS remain hybrid where filtering or Gram construction occurs on the host, and nonlinear kernels are practically limited by O(n²) storage.")
paragraph(main, "float32 reduces the representation size of input and many intermediates, which was essential for the million-row and extreme-response workflows, but it is not a universal speed or process-memory guarantee. The current NMR results show small route-dependent metric differences, and complete-process RSS includes data, runtime libraries and allocator state. Precision should therefore be selected according to feasibility and verified numerical behaviour rather than assumed superiority.")
paragraph(main, "The study has limitations. Fixed prepared splits primarily support paired computational comparison and do not replace subject-grouped external validation. The broad independent-software panel is an end-to-end workflow comparison with different native precisions and model objects. Accelerator ratios depend on two workstations and include initialization overhead. The ImageNet experiment is an engineering analogue for foundation-model embeddings, not biomedical evidence. Future work will expand validation on other GPU architectures, strengthen route-specific numerical diagnostics and refine automatic dispatch using controlled multi-factor scaling experiments.")

heading(main, "5. Conclusions")
paragraph(main, "fastPLS combines a compiled sequential SIMPLS path with compact prediction, rSVD and optional CUDA and Metal execution. It extends practical PLS analysis to response and sample dimensions that were previously difficult to process in R, while preserving explicit reporting of precision, backend residency and numerical controls. The NMR application demonstrates the value of the implementation for high-response biomedical prediction; appropriate solver and backend choices remain workload dependent.")

heading(main, "Declarations")
paragraph(main, "Acknowledgements: The authors thank the University of Cape Town's ICTS High Performance Computing team for providing a high-performance computing facility for this study (https://ucthpc.uct.ac.za/).")
paragraph(main, "Funding: This research received no specific grant from funding agencies in the public, commercial or not-for-profit sectors.")
paragraph(main, "Competing interests: The authors declare no competing financial interests or personal relationships that could have influenced this work.")
paragraph(main, "Data and software availability: fastPLS is available through Bioconductor and at https://github.com/tkcaccia/fastPLS. Executable benchmark scripts, result tables and restricted-data acquisition instructions accompany the source repository. Public datasets remain subject to their source licences and access conditions.")

heading(main, "References")
references = [
    "[1] Wold S, Sjöström M, Eriksson L. PLS-regression: a basic tool of chemometrics. Chemometrics and Intelligent Laboratory Systems. 2001;58:109–130.",
    "[2] Cacciatore S, Wium M, Licari C, et al. Inflammatory metabolic profile of South African patients with prostate cancer. Cancer & Metabolism. 2021;9:29. doi:10.1186/s40170-021-00265-6.",
    "[3] de Jong S. SIMPLS: an alternative approach to partial least squares regression. Chemometrics and Intelligent Laboratory Systems. 1993;18:251–263.",
    "[4] Trygg J, Wold S. Orthogonal projections to latent structures (O-PLS). Journal of Chemometrics. 2002;16:119–128.",
    "[5] Rosipal R, Trejo LJ. Kernel partial least squares regression in reproducing kernel Hilbert space. Journal of Machine Learning Research. 2001;2:97–123.",
    "[6] Mevik B-H, Wehrens R. The pls package: principal component and partial least squares regression in R. Journal of Statistical Software. 2007;18:1–23.",
    "[7] Andersson CA. IKPLS: fast improved kernel partial least squares algorithms. Journal of Open Source Software. 2024;9:6533. doi:10.21105/joss.06533.",
    "[8] Halko N, Martinsson P-G, Tropp JA. Finding structure with randomness: probabilistic algorithms for constructing approximate matrix decompositions. SIAM Review. 2011;53:217–288.",
    "[9] Vignoli A, et al. Multivariate prediction of diffusion-edited NMR spectra from NOESY data. Nature Communications. 2025. doi:10.1038/s41467-025-65294-x.",
    "[10] Oquab M, Darcet T, Moutakanni T, et al. DINOv2: learning robust visual features without supervision. Transactions on Machine Learning Research. 2024.",
    "[11] NVIDIA Corporation. CUDA Toolkit documentation: cuBLAS, cuSOLVER and cuRAND libraries. https://docs.nvidia.com/cuda/.",
    "[12] Apple Inc. Metal Performance Shaders documentation. https://developer.apple.com/metal/Metal-Performance-Shaders/.",
    "[13] Chen RJ, Ding T, Lu MY, et al. Towards a general-purpose foundation model for computational pathology. Nature Medicine. 2024;30:850–862. doi:10.1038/s41591-024-02857-3.",
    "[14] Xu H, Usuyama N, Bagga J, et al. A whole-slide foundation model for digital pathology from real-world data. Nature. 2024;630:181–188. doi:10.1038/s41586-024-07441-w.",
    "[15] Krizhevsky A, Hinton G. Learning multiple layers of features from tiny images. Technical report. University of Toronto; 2009.",
    "[16] Deng J, Dong W, Socher R, Li LJ, Li K, Fei-Fei L. ImageNet: a large-scale hierarchical image database. IEEE Conference on Computer Vision and Pattern Recognition. 2009:248–255. doi:10.1109/CVPR.2009.5206848.",
]
for ref in references:
    paragraph(main, ref)


supp = Document()
configure(supp, supplement=True)
set_core_properties(supp, "Supplementary material: " + title,
                    "Supplementary methods, tables and figures")
supp.add_heading("Supplementary material", 0)
paragraph(supp, title)

heading(supp, "S1. Dataset construction and preprocessing")
paragraph(supp, "All paired computational comparisons used prepared training and test objects. Preprocessing parameters were estimated from training data and applied unchanged to the corresponding test matrix. Subject- or donor-level grouping was retained through constrain where identifiers were available; otherwise, the fixed split is interpreted as a computational benchmark rather than an estimate of independent-subject generalization.")

dataset_body = [
    ["TCGA-HNSC methylation", "Classification", "520", "58", "782", "2"],
    ["CCLE", "Classification", "547", "71", "1,000", "18"],
    ["TCGA-BRCA", "Classification", "756", "88", "1,000", "5"],
    ["MetRef", "Classification", "773", "100", "375", "22"],
    ["TCGA Pan-Cancer", "Classification", "3,000", "982", "850", "32"],
    ["GTEx v8", "Classification", "3,000", "797", "1,000", "32"],
    ["Retina", "Classification", "22,402", "22,406", "50", "12"],
    ["Tabula Muris", "Classification", "50,043", "50,059", "50", "32"],
    ["CIFAR-100", "Classification", "50,000", "10,000", "768", "100"],
    ["CBMC CITE-seq", "Regression", "7,755", "862", "1,000", "10"],
    ["PRISM", "Regression", "479", "54", "1,000", "4,686"],
    ["NMR", "Regression", "1,200", "321", "13,000", "28,355"],
]
add_table(supp, "Table S1. Prepared benchmark dimensions.",
          ["Dataset", "Task", "Training n", "Test n", "p", "q"], dataset_body, 6.8)

acquisition_body = [
    ["MetRef", "KODAMA package data; zero columns removed, then normalization and scaling", "Acquisition script; object not redistributed"],
    ["CIFAR-100", "University of Toronto public archive; stored feature representation", "Download/preparation script"],
    ["CBMC CITE-seq", "GEO GSE100866", "Download/preparation script"],
    ["Retina", "GEO GSE63472; 50-dimensional prepared representation", "Download/preparation script"],
    ["Tabula Muris", "Bioconductor ExperimentHub resource", "Bioconductor acquisition script"],
    ["CCLE, GTEx, TCGA, PRISM", "Public project resources subject to source terms", "Acquisition and harmonization scripts"],
    ["NMR", "Study-specific prepared matrices associated with Vignoli et al. [9]", "Access subject to original study conditions"],
    ["ImageNet/DINOv2", "Derived representation; no image files redistributed", "Current stress-test runner and manifest"],
]
add_table(supp, "Table S2. Data acquisition and redistribution status.",
          ["Dataset", "Source/preparation", "Distributed material"], acquisition_body, 6.8)

heading(supp, "S2. Algorithmic complexity and backend residency")
complexity_body = [
    ["PLS-SVD, explicit", "Form XᵀY: O(npq); one retained rSVD", "O(pq + (p+q)A)", "CPU; resident CUDA where supported; Metal route-dependent"],
    ["PLS-SVD, implicit", "Repeated Xᵀ(YΩ), Yᵀ(XQ)", "O((n+p+q)l), no p by q S", "Route selected by shape and backend"],
    ["SIMPLS", "Sequential components plus deflation", "O(pq + (2p+q)A)", "CPU; resident CUDA where supported; Metal hybrid/host-assisted"],
    ["OPLS", "Orthogonal filter plus predictive core", "Filter basis plus inner model", "CPU; accelerator route may be hybrid"],
    ["Kernel PLS, linear", "Linear shortcut", "As selected linear core", "CPU/CUDA/Metal according to core"],
    ["Kernel PLS, nonlinear", "Kernel construction and centred sample-space fit", "O(n²) Gram matrix", "Host Gram stage; accelerator core may be hybrid"],
    ["Compact prediction", "XnewR and latent response mapping", "O(ntest A + (p+q)A)", "Supported CPU/CUDA/Metal routes"],
]
add_table(supp, "Table S3. Dominant operations, storage and residency.",
          ["Route", "Dominant work", "Additional storage", "Residency"], complexity_body, 6.5)
paragraph(supp, "Here A is the maximum retained component count and l is the randomized sketch width. Explicit means that the p by q cross-covariance is stored. Implicit means that only its action on a narrow matrix is evaluated, so S is not stored.")

heading(supp, "S3. Numerical validation and implementation ablation")
exact_prefixes = sum(int(number(r["component_prefixes"])) for r in exact_validation)
exact_failures = sum(int(number(r["convergence_failures"])) for r in exact_validation)
exact_prediction_error = max(number(r["max_prediction_relative_error"])
                             for r in exact_validation)
exact_label_values = [number(r["min_classification_label_agreement"])
                      for r in exact_validation
                      if math.isfinite(number(r["min_classification_label_agreement"]))]
validation_body = [[
    "SIMPLS component-wise dense reference", str(exact_prefixes), str(exact_failures),
    fmt(exact_prediction_error, 6), "NA",
    fmt(min(exact_label_values), 4) if exact_label_values else "NA",
    "Exact-reference cases; includes near-tied singular values",
]]
for r in rsvd_validation:
    validation_body.append([
        f"rSVD qualification, {r['backend']}", r["comparisons"],
        str(int(number(r["comparisons"])) - int(number(r["comparisons_within_tolerance"]))),
        fmt(r["max_prediction_relative_error"], 6),
        fmt(r["min_prediction_correlation"], 6),
        fmt(r["min_label_agreement"], 4),
        f"Profiles {r['control_profiles']}; controls {r['effective_controls']}",
    ])
for r in family_validation:
    validation_body.append([
        r["family"], r["runs"], r["failures"],
        fmt(r["max_prediction_relative_error"], 6),
        fmt(r["min_prediction_correlation"], 6),
        fmt(r["min_label_agreement"], 4),
        "Deterministic float64 CPU estimator check",
    ])
add_table(supp, "Table S4. Consolidated numerical-validation summary.",
          ["Evidence", "Comparisons", "Failures", "Maximum prediction error", "Minimum correlation", "Minimum label agreement", "Scope"],
          validation_body, 5.8)
paragraph(supp, "The component-wise SIMPLS validation compares the optimized deterministic execution with a dense reference on well-conditioned, collinear, rank-deficient, high-response, p<n, p>n and near-tied cases. rSVD qualification uses route-specific profiles and predefined numerical tolerances; meeting these tolerances is not described as exact equality. Prefix-level errors and all replicate records remain in the benchmark archive.")

ablation_body = []
for optimization in sorted({r["optimization"] for r in ablation}):
    current = [r for r in ablation
               if r["optimization"] == optimization and r["optimization_applicable"] == "TRUE"]
    if not current:
        continue
    speedups = [number(r["speedup"]) for r in current]
    rss = [number(r["rss_reduction_pct"]) for r in current]
    differences = [number(r["metric_abs_diff"]) for r in current]
    agreements = [number(r["prediction_agreement_min"]) for r in current]
    ablation_body.append([
        optimization.replace("_", " "), str(len(current)),
        f"{min(speedups):.2f}–{max(speedups):.2f}",
        f"{min(rss):.1f}–{max(rss):.1f}",
        fmt(max(differences), 6), fmt(min(agreements), 4),
    ])
add_table(supp, "Table S5. Same-code multidataset SIMPLS ablation.",
          ["Optimization", "Applicable datasets", "Speed-up range", "RSS reduction range (%)", "Maximum metric difference", "Minimum prediction agreement"],
          ablation_body, 6.0)
paragraph(supp, "A speed-up above one favours the optimized state. Negative RSS reduction indicates a larger measured complete-process increment. Individual optimizations are shape dependent and are therefore combined by the public dispatcher rather than claimed to accelerate every matrix regime.")

software_capability_body = [
    ["fastPLS", "Compiled C++/linked BLAS", "Yes; verified OpenBLAS build", "CUDA", "Metal", "float32/float64, route-specific"],
    ["IKPLS", "NumPy or JAX", "Runtime dependent", "JAX-compatible", "Not evaluated", "float32/float64, runtime dependent"],
    ["pls", "R/compiled numerical libraries", "Linked BLAS only", "No", "No", "R numeric float64"],
    ["plsgenomics", "R/compiled dependencies", "No package-level control", "No", "No", "R numeric float64"],
    ["mdatools", "R/compiled dependencies", "No package-level control", "No", "No", "R numeric float64"],
    ["plsdepot", "R", "No package-level control", "No", "No", "R numeric float64"],
    ["pcv", "R/compiled dependencies", "No package-level control", "No", "No", "R numeric float64"],
    ["chemometrics", "R/compiled dependencies", "No package-level control", "No", "No", "R numeric float64"],
    ["mixOmics", "R/compiled dependencies", "Linked BLAS only", "No", "No", "R numeric float64"],
    ["spls", "R/compiled dependencies", "No package-level control", "No", "No", "R numeric float64"],
]
add_table(supp, "Table S6. Computational capabilities of compared implementations.",
          ["Implementation", "CPU route", "Multiple CPU threads", "NVIDIA GPU", "Apple GPU", "Precision"],
          software_capability_body, 5.8)

heading(supp, "S4. Complete CPU and accelerator results")
backend_family_names = {
    "plssvd": "PLS-SVD", "simpls": "SIMPLS",
    "opls": "OPLS", "kernelpls": "kernel PLS",
}
backend_body = []
backend_memory_body = []
for r in fig2:
    backend_body.append([
        r["platform"], r["dataset"],
        backend_family_names.get(r["method"], r["method"]), r["ncomp"],
        fmt(r["cpu_time_sec"], 3), fmt(r["accelerator_time_sec"], 3),
        fmt(r["ratio"], 2), fmt(r["cpu_metric"], 4),
        fmt(r["accelerator_metric"], 4), r["execution_route"],
    ])
    backend_memory_body.append([
        r["platform"], r["dataset"],
        backend_family_names.get(r["method"], r["method"]), r["ncomp"],
        fmt(r["cpu_incremental_rss_mib"], 1),
        fmt(r["accelerator_incremental_rss_mib"], 1),
        fmt(r["memory_ratio"], 2), r["execution_route"],
    ])
add_table(supp, "Table S7. Complete selected-point CPU/CUDA and CPU/Metal comparison.",
          ["Platform", "Dataset", "Family", "A", "CPU s", "Accelerator s", "Time ratio", "CPU metric", "Accelerator metric", "Route"], backend_body, 5.8)
add_table(supp, "Table S8. Selected-point incremental host-memory comparison.",
          ["Platform", "Dataset", "Family", "A", "CPU RSS MiB", "Accelerator RSS MiB", "RSS ratio", "Route"], backend_memory_body, 5.8)
paragraph(supp, "The metric is accuracy for classification and RMSD for regression. CPU/accelerator ratios above one favour the accelerator. Values are paired within workstation. This table retains all tested timings rather than suppressing rows on the basis of metric disagreement.")

heading(supp, "S5. Component paths across benchmark datasets")
dataset_names = {
    "cbmc_citeseq": "CBMC CITE-seq", "ccle": "CCLE",
    "cifar100": "CIFAR-100", "gtex_v8": "GTEx v8", "metref": "MetRef",
    "prism": "PRISM", "retina": "Retina", "tabula": "Tabula Muris",
    "tcga_brca": "TCGA-BRCA",
    "tcga_hnsc_methylation": "TCGA-HNSC methylation",
    "tcga_pan_cancer": "TCGA Pan-Cancer",
}
family_names = {
    "plssvd": "PLS-SVD", "simpls": "SIMPLS",
    "opls": "OPLS", "kernelpls": "kernel PLS",
}
component_selection_body = [[
    dataset_names.get(r["dataset"], r["dataset"]),
    family_names.get(r["method"], r["method"]),
    r["selected_ncomp"], r["selection_metric"], r["selection_status"],
    f"{r['grid_min']}–{r['grid_max']}", r["intrinsic_limit"],
    r["selection_oversample"], r["selection_power"],
] for r in component_selection]
add_table(supp, "Table S9. Training-selected component counts for the current benchmark panel.",
          ["Dataset", "Family", "Selected A", "Metric", "Status", "Grid", "Rank limit", "Oversampling", "Power"],
          component_selection_body, 5.8)

correlation_body = [[
    r["platform"], dataset_names.get(r["dataset"], r["dataset"]),
    family_names.get(r["method"], r["method"]), r["backend"],
    r["n_path_points"], fmt(r["rho_metric"], 3),
    fmt(r["rho_total_time"], 3), fmt(r["rho_incremental_rss"], 3),
] for r in component_correlations]
add_table(supp, "Table S10. Spearman associations with requested component count.",
          ["Computer", "Dataset", "Family", "Backend", "Path points", "Metric rho", "Time rho", "RSS rho"],
          correlation_body, 5.2)
paragraph(supp, "Positive time or RSS correlations indicate increasing computational cost with additional components. The sign of the predictive-metric correlation is interpreted according to the endpoint: larger accuracy is better, whereas smaller RMSD is better. The complete per-component medians, interquartile ranges, controls and execution routes accompany the source files.")

component_figure_order = [
    "ccle", "cifar100", "gtex_v8", "metref", "retina", "tabula",
    "tcga_brca", "tcga_hnsc_methylation", "tcga_pan_cancer",
    "cbmc_citeseq", "prism",
]
for figure_index, dataset_id in enumerate(component_figure_order, start=1):
    add_figure(
        supp,
        f"component_path_{dataset_id}.png",
        f"Figure S{figure_index}. {dataset_names[dataset_id]} component paths. Predictive metric, total fitting-plus-prediction time and incremental host RSS are shown for PLS-SVD, SIMPLS, OPLS and kernel PLS on the current CPU and available accelerator routes; dotted vertical lines mark the training-selected component count for each family.",
        6.45,
    )

heading(supp, "S6. NMR component selection and fixed-component comparison")
selection_body = [[
    family_names.get(r["family"], r["family"]),
    r["selected_ncomp"], r["minimum_mean_ncomp"],
    fmt(r["one_se_threshold"], 7), r["eligible_ncomp"].replace(",", ", "),
    r["largest_tested_ncomp"], r["n_splits_successful"],
] for r in nmr_decision]
add_table(supp, "Table S11. NMR one-standard-error component decisions.",
          ["Family", "Selected A", "Mean-minimum A", "One-SE threshold", "Eligible A", "Grid maximum", "Successful splits"], selection_body, 6.8)
add_figure(supp, "figureS1_nmr_component_selection.png", "Figure S12. Training-only NMR component selection. Lines show mean validation RMSD across five paired splits; error bars show standard errors. The selected value is the smallest component count within one standard error of the minimum mean RMSD.", 6.45)

nmr_body = [[
    r["implementation"], r["precision"], r["ncomp"],
    fmt(r["total_time_sec"], 3), fmt(r["RMSD"], 7), fmt(r["Q2"], 4),
    fmt(r["incremental_rss_mib"], 1), fmt(r["incremental_gpu_mib"], 1),
] for r in fig3]
add_table(supp, "Table S12. NMR fixed 165-component implementation comparison.",
          ["Implementation", "Precision", "A", "Total s", "RMSD", "Q²", "RSS increment MiB", "GPU increment MiB"], nmr_body, 6.5)
paragraph(supp, "The fixed 165-component analysis reproduces the component workload of the deposited scientific implementation. It intentionally separates this computational comparison from family-specific training-only selection. The deposited row differs in solver, implementation and hardware; it is not an isolated backend comparison.")

heading(supp, "S7. Verified CPU thread scaling")
multicore_body = [[
    r["workload"], r["active_openblas_threads"], r["n_train"], r["n_test"],
    r["p"], r["q"], r["ncomp"], r["repetitions"], fmt(r["median_sec"], 3),
    f"{fmt(r['q1_sec'], 3)}–{fmt(r['q3_sec'], 3)}", fmt(r["speedup"], 2),
    r["metric_name"], fmt(r["metric_value"], 6), r["prediction_agreement"],
] for r in multicore]
add_table(supp, "Table S13. Verified OpenBLAS thread-scaling benchmark.",
          ["Workload", "Threads", "Train n", "Test n", "p", "q", "A", "Runs", "Median s", "IQR s", "Speed-up", "Metric", "Value", "Same predictions"],
          multicore_body, 5.2)
add_figure(supp, "figureS13_multicore_scaling.png", "Figure S13. Verified CPU thread scaling. Speed-up is relative to the median one-thread time for each controlled workload; bars span the speed-ups obtained from the first and third timing quartiles. The OpenBLAS thread count was probed directly before each fit, and predictions were identical across settings.", 6.45)

heading(supp, "S8. Precision and capability interpretation")
capability_body = [
    ["SIMPLS", "CPU", "float64/float32", "Compiled", "Validated public path"],
    ["SIMPLS", "CUDA", "float64/float32", "Resident core and prediction", "Validated; CUDA availability required"],
    ["SIMPLS", "Metal", "float32", "Metal products and compact prediction; component extraction route-dependent", "Hybrid/host-assisted; float64 returns an error"],
    ["PLS-SVD", "CPU", "float64/float32", "Compiled", "Validated public path"],
    ["PLS-SVD", "CUDA", "float64/float32", "Resident decomposition/prediction", "Validated; CUDA availability required"],
    ["PLS-SVD", "Metal", "float32", "Metal products and compact prediction; reduced decomposition route-dependent", "Hybrid/host-assisted; float64 returns an error"],
    ["OPLS", "CPU", "float64/float32", "Compiled", "Supported"],
    ["OPLS", "CUDA/Metal", "route dependent", "Host filter plus accelerator predictive core", "Hybrid"],
    ["Kernel PLS, linear", "CPU/CUDA/Metal", "route dependent", "Linear shortcut", "Supported according to core"],
    ["Kernel PLS, nonlinear", "CPU/CUDA/Metal", "route dependent", "Host Gram construction", "Hybrid; O(n²) host storage"],
    ["LDA", "CPU", "float64/float32", "Compiled covariance and Cholesky", "Supported"],
    ["LDA", "CUDA", "float64/float32", "Device score/covariance path where eligible", "Supported"],
    ["LDA", "Metal", "float32", "Metal score projection; CPU float32 discriminant", "Hybrid; float64 unavailable"],
]
add_table(supp, "Table S14. Public precision and backend capability matrix.",
          ["Family/head", "Backend", "Precision", "Residency", "Status"], capability_body, 6.5)
paragraph(supp, "float32 support means that the principal supported numerical buffers use single precision. It does not imply that every R bookkeeping object or complete-process allocation is half the corresponding float64 measurement. An unsupported backend or precision combination raises an informative error before fitting; no CPU fallback is used.")

heading(supp, "S9. ImageNet stress test")
if has_imagenet:
    image_body = [[r.get("classifier", ""), r.get("ncomp_requested", ""),
                   fmt(r.get("top1_accuracy"), 4), fmt(r.get("top5_accuracy"), 4),
                   fmt(r.get("total_time_sec"), 2), fmt(r.get("peak_rss_mb"), 0),
                   fmt(r.get("peak_gpu_mb"), 0), r.get("fit_residency", "")]
                  for r in image]
    add_table(supp, "Table S15. Current-release ImageNet/DINOv2 float32 SIMPLS stress test.",
              ["Head", "A", "Top-1", "Top-5", "Total s", "Peak RSS MiB", "Peak GPU MiB", "Route"], image_body, 6.5)
else:
    paragraph(supp, "The current-release ImageNet calculation has not completed. Earlier package-version and hybrid results are intentionally excluded from this document.")

heading(supp, "S10. Reproducibility and software checks")
repro_body = [
    ["Package", "fastPLS 0.99.39", "Current manuscript, tables, figures, vignette and manual"],
    ["macOS", "Apple M3, 8 CPU cores, 8 GB unified memory", "CPU and Metal; R CMD check tests and Metal integration"],
    ["CUDA workstation", "Intel Core i7-13700; 32 GB RAM; NVIDIA GeForce RTX 5060 Ti, 16 GB", "CPU and CUDA benchmark panels"],
    ["R package checks", "R CMD check", "Tests, examples, documentation and vignette completed locally"],
    ["Bioconductor checks", "BiocCheck", "0 errors; remaining style and repository-status notes are not numerical failures"],
]
add_table(supp, "Table S16. Reproducibility and platform summary.",
          ["Item", "Configuration", "Role/status"], repro_body, 6.8)
paragraph(supp, "Benchmark scripts record requested method, component count, precision, seed, rSVD controls, executed route, timing, metrics and completion status. CUDA timing includes transfer and synchronization in the public workflow. Metal float64 is tested as an informative error, not as a CPU fallback.")

main_path = OUT / "fastPLS_manuscript_0.99.39_current.docx"
supp_path = OUT / "fastPLS_supplement_0.99.39_current.docx"
main.save(main_path)
supp.save(supp_path)
print(main_path)
print(supp_path)
print(f"ImageNet current results included: {has_imagenet}")
