#!/usr/bin/env bash
set -euo pipefail

: "${FASTPLS_SOURCE_ROOT:?Set FASTPLS_SOURCE_ROOT}"
: "${FASTPLS_EVIDENCE_ROOT:?Set FASTPLS_EVIDENCE_ROOT}"
: "${FASTPLS_IKPLS_PANEL_SUMMARY:?Set FASTPLS_IKPLS_PANEL_SUMMARY}"
: "${FASTPLS_IKPLS_LARGE_DIR:?Set FASTPLS_IKPLS_LARGE_DIR}"
: "${FASTPLS_CURRENT_NMR_ROOT:?Set FASTPLS_CURRENT_NMR_ROOT}"
: "${FASTPLS_CURRENT_EVIDENCE:?Set FASTPLS_CURRENT_EVIDENCE}"
: "${FASTPLS_NMR_LINUX_EVIDENCE:?Set FASTPLS_NMR_LINUX_EVIDENCE}"
: "${FASTPLS_NMR_MAC_EVIDENCE:?Set FASTPLS_NMR_MAC_EVIDENCE}"
: "${FASTPLS_MANUSCRIPT_OUTPUT:?Set FASTPLS_MANUSCRIPT_OUTPUT}"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
python="${FASTPLS_PYTHON:-python3}"

FASTPLS_SOURCE_ROOT="${FASTPLS_SOURCE_ROOT}" \
FASTPLS_EVIDENCE_ROOT="${FASTPLS_EVIDENCE_ROOT}" \
FASTPLS_IKPLS_PANEL_SUMMARY="${FASTPLS_IKPLS_PANEL_SUMMARY}" \
FASTPLS_IKPLS_LARGE_DIR="${FASTPLS_IKPLS_LARGE_DIR}" \
FASTPLS_CURRENT_NMR_ROOT="${FASTPLS_CURRENT_NMR_ROOT}" \
FASTPLS_MANUSCRIPT_OUTPUT="${FASTPLS_MANUSCRIPT_OUTPUT}" \
    Rscript "${root}/tools/build_current_09939_figures.R" \
        "${FASTPLS_SOURCE_ROOT}" "${FASTPLS_MANUSCRIPT_OUTPUT}"

Rscript "${root}/tools/build_current_09940_evidence.R" \
    "${FASTPLS_CURRENT_EVIDENCE}" \
    "${FASTPLS_MANUSCRIPT_OUTPUT}" \
    "${FASTPLS_MANUSCRIPT_OUTPUT}/tables/figure1_independent_implementation_data.csv"

Rscript "${root}/tools/build_nmr_figure3.R" \
    "${FASTPLS_NMR_LINUX_EVIDENCE}" \
    "${FASTPLS_NMR_MAC_EVIDENCE}" \
    "${FASTPLS_MANUSCRIPT_OUTPUT}"

"${python}" "${root}/tools/build_current_09939_documents.py"
