#!/usr/bin/env python3
"""Build the current fastPLS 0.99.65 manuscript and supplement.

The builder accepts only the current-release tables and figures generated by
release-evidence scripts. ImageNet is included only when the current
result and figure exist, preventing accidental reuse of older runs.
"""

from __future__ import annotations

import csv
import math
import os
from pathlib import Path

from docx import Document
from docx.enum.section import WD_ORIENT, WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


EXTRA = Path(__file__).resolve().parents[1]
PKG = Path(os.environ.get("FASTPLS_SOURCE_ROOT", EXTRA.parent / "fastPLS"))
if "FASTPLS_MANUSCRIPT_OUTPUT" not in os.environ:
    raise RuntimeError("Set FASTPLS_MANUSCRIPT_OUTPUT outside the Git checkouts")
BASE = Path(os.environ["FASTPLS_MANUSCRIPT_OUTPUT"])
FIG = BASE / "figures"
TAB = BASE / "tables"
OUT = BASE / "documents"
OUT.mkdir(parents=True, exist_ok=True)


def rows(name: str) -> list[dict[str, str]]:
    path = TAB / name
    if not path.exists():
        raise FileNotFoundError(f"Missing current evidence: {path}")
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def number(value: str | float | int | None) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return math.nan


def fmt(value: str | float | int | None, digits: int = 3) -> str:
    val = number(value)
    if not math.isfinite(val):
        return "NA"
    return f"{val:.{digits}f}"


def scientific(value: float, digits: int = 1) -> str:
    if not math.isfinite(value):
        return "NA"
    mantissa, exponent = f"{value:.{digits}e}".split("e")
    superscript = str.maketrans("-0123456789", "⁻⁰¹²³⁴⁵⁶⁷⁸⁹")
    return f"{mantissa} × 10{str(int(exponent)).translate(superscript)}"


def display_backend(value: str) -> str:
    return {
        "cpu": "CPU",
        "cuda": "CUDA",
        "metal": "Metal",
    }.get(value.lower(), value)


def display_family(value: str) -> str:
    return {
        "plssvd": "PLS-SVD",
        "simpls": "SIMPLS",
        "opls": "OPLS",
        "kernelpls": "kernel PLS",
    }.get(value.lower(), value)


def display_route(value: str) -> str:
    words = value.replace("cuda", "CUDA").replace("metal", "Metal")
    return words.replace("cpu", "CPU")


def add_line_numbers(section) -> None:
    sect_pr = section._sectPr
    old = sect_pr.find(qn("w:lnNumType"))
    if old is not None:
        sect_pr.remove(old)
    node = OxmlElement("w:lnNumType")
    node.set(qn("w:countBy"), "1")
    node.set(qn("w:restart"), "continuous")
    node.set(qn("w:distance"), "360")
    sect_pr.append(node)


def configure(doc: Document, supplement: bool = False) -> None:
    section = doc.sections[0]
    section.orientation = WD_ORIENT.PORTRAIT
    section.page_width = Inches(8.27)
    section.page_height = Inches(11.69)
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.75 if supplement else 0.85)
    section.right_margin = Inches(0.65 if supplement else 0.75)
    add_line_numbers(section)

    normal = doc.styles["Normal"]
    normal.font.name = "Arial"
    normal.font.size = Pt(9.5 if supplement else 10)
    normal.font.color.rgb = RGBColor(0, 0, 0)
    normal.paragraph_format.space_after = Pt(3)
    normal.paragraph_format.line_spacing = 1.08
    for name, size in (("Title", 17), ("Heading 1", 13), ("Heading 2", 11)):
        style = doc.styles[name]
        style.font.name = "Arial"
        style.font.size = Pt(size)
        style.font.bold = True
        style.font.color.rgb = RGBColor(0, 0, 0)


def set_cell_shading(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shading = tc_pr.find(qn("w:shd"))
    if shading is None:
        shading = OxmlElement("w:shd")
        tc_pr.append(shading)
    shading.set(qn("w:fill"), fill)


def set_cell_margins(cell, top: int = 55, start: int = 65,
                     bottom: int = 55, end: int = 65) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    margins = tc_pr.first_child_found_in("w:tcMar")
    if margins is None:
        margins = OxmlElement("w:tcMar")
        tc_pr.append(margins)
    for name, value in (("top", top), ("start", start),
                        ("bottom", bottom), ("end", end)):
        node = margins.find(qn(f"w:{name}"))
        if node is None:
            node = OxmlElement(f"w:{name}")
            margins.append(node)
        node.set(qn("w:w"), str(value))
        node.set(qn("w:type"), "dxa")


def keep_table_row_together(row, repeat_header: bool = False) -> None:
    tr_pr = row._tr.get_or_add_trPr()
    cant_split = OxmlElement("w:cantSplit")
    tr_pr.append(cant_split)
    if repeat_header:
        header = OxmlElement("w:tblHeader")
        header.set(qn("w:val"), "true")
        tr_pr.append(header)


def paragraph(doc: Document, text: str, bold_prefix: str | None = None):
    par = doc.add_paragraph()
    if bold_prefix and text.startswith(bold_prefix):
        par.add_run(bold_prefix).bold = True
        par.add_run(text[len(bold_prefix):])
    else:
        par.add_run(text)
    return par


def heading(doc: Document, text: str, level: int = 1):
    return doc.add_heading(text, level=level)


def add_table(doc: Document, caption: str, headers: list[str], body: list[list[str]],
              font_size: float = 7.2) -> None:
    cap = doc.add_paragraph()
    cap.add_run(caption).bold = True
    cap.paragraph_format.keep_with_next = True
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    for j, value in enumerate(headers):
        table.rows[0].cells[j].text = value
    for values in body:
        cells = table.add_row().cells
        for j, value in enumerate(values):
            cells[j].text = str(value)
    keep_table_row_together(table.rows[0], repeat_header=True)
    for i, row in enumerate(table.rows):
        if i > 0:
            keep_table_row_together(row)
        for cell in row.cells:
            cell.vertical_alignment = 1
            set_cell_margins(cell)
            if i == 0:
                set_cell_shading(cell, "D9E2F3")
            elif i % 2 == 0:
                set_cell_shading(cell, "F6F8FA")
            for par in cell.paragraphs:
                par.paragraph_format.space_after = Pt(0)
                par.paragraph_format.line_spacing = 1.0
                for run in par.runs:
                    run.font.name = "Arial"
                    run.font.size = Pt(font_size)
                    if i == 0:
                        run.bold = True


def add_figure(doc: Document, filename: str, caption: str, width: float) -> None:
    path = FIG / filename
    if not path.exists():
        raise FileNotFoundError(f"Missing current figure: {path}")
    par = doc.add_paragraph()
    par.alignment = WD_ALIGN_PARAGRAPH.CENTER
    par.paragraph_format.keep_with_next = True
    par.add_run().add_picture(str(path), width=Inches(width))
    cap = doc.add_paragraph()
    cap.paragraph_format.keep_together = True
    cap.add_run(caption).italic = True


def add_landscape_figure(doc: Document, filename: str, caption: str) -> None:
    landscape = doc.add_section(WD_SECTION.NEW_PAGE)
    landscape.orientation = WD_ORIENT.LANDSCAPE
    landscape.page_width = Inches(11.69)
    landscape.page_height = Inches(8.27)
    landscape.top_margin = Inches(0.45)
    landscape.bottom_margin = Inches(0.45)
    landscape.left_margin = Inches(0.55)
    landscape.right_margin = Inches(0.55)
    add_line_numbers(landscape)
    add_figure(doc, filename, caption, 10.45)

    portrait = doc.add_section(WD_SECTION.NEW_PAGE)
    portrait.orientation = WD_ORIENT.PORTRAIT
    portrait.page_width = Inches(8.27)
    portrait.page_height = Inches(11.69)
    portrait.top_margin = Inches(0.7)
    portrait.bottom_margin = Inches(0.7)
    portrait.left_margin = Inches(0.85)
    portrait.right_margin = Inches(0.75)
    add_line_numbers(portrait)


def set_core_properties(doc: Document, title: str, subject: str) -> None:
    props = doc.core_properties
    props.title = title
    props.subject = subject
    props.author = "Dupe Ojo; Alessia Vignoli; Stefano Cacciatore; Leonardo Tenori"
    props.keywords = "partial least squares; SIMPLS; randomized SVD; CUDA; Metal; NMR"


fig1 = rows("figure1_independent_implementation_data.csv")
for row in fig1:
    # The six-panel table uses implementation-neutral column names. Preserve
    # the historical aliases below so the remaining document calculations can
    # consume one canonical current-release table.
    row.setdefault("display", row.get("implementation", ""))
    row.setdefault("time_sec", row.get("total_sec", ""))
    row.setdefault("memory_mib", row.get("peak_rss_mib", ""))
ikpls_panel = rows("ikpls_complete_panel_summary.csv")
ikpls_all = rows("ikpls_all_dataset_status.csv")
python_panel = rows("python_pls_panel_summary.csv") if (
    TAB / "python_pls_panel_summary.csv"
).exists() else []
python_status = rows("python_pls_panel_status.csv") if (
    TAB / "python_pls_panel_status.csv"
).exists() else []
python_panel = [
    row for row in python_panel
    if row.get("implementation") == "sklearn_plsregression"
]
python_status = [
    row for row in python_status
    if row.get("implementation") == "sklearn_plsregression"
]
python_large = rows("python_pls_large_all_runs.csv") if (
    TAB / "python_pls_large_all_runs.csv"
).exists() else []
fig2 = rows("figure2_backend_runtime_ratios.csv")
fig3 = rows("figure3_nmr_fixed165_summary.csv")
nmr_path = rows("supplement_nmr_component_path.csv")
nmr_decision = rows("supplement_nmr_component_decision.csv")
component_selection = rows("component_selection.csv")
component_correlations = rows("component_metric_correlations.csv")
multicore = rows("multicore_scaling_summary.csv")
precision = rows("precision_float32_float64_summary.csv")
solver = rows("rsvd_irlba_summary.csv")
solver_paired = rows("rsvd_irlba_paired_summary.csv")
exact_validation = rows("simpls_exact_reference_case_summary.csv")
rsvd_validation = rows("rsvd_qualification_summary.csv")
family_validation = rows("opls_kernel_estimator_validation_summary.csv")
ablation = rows("simpls_multidataset_ablation_effects.csv")
with (
    EXTRA / "benchmark/current_release_evidence/figure1_component_contract.csv"
).open(newline="", encoding="utf-8") as handle:
    figure1_contract = list(csv.DictReader(handle))

fast = [r for r in fig1 if r["display"].startswith("fastPLS") and math.isfinite(number(r["time_sec"]))]
datasets = sorted({r["dataset"] for r in fast})
ordinary_datasets = [
    dataset for dataset in datasets if dataset not in {"imagenet", "nmr"}
]
fastest_r_or_tied = 0
fastest_ikpls_or_tied = 0
r_comparable_count = 0
ikpls_comparable_count = 0
workflow_speedups = {}
ikpls_speedups = {}
for dataset in datasets:
    ftime = min(number(r["time_sec"]) for r in fast if r["dataset"] == dataset)
    python_displays = {
        "IKPLS",
        "scikit-learn / PLSRegression",
    }
    external_r = [number(r["time_sec"]) for r in fig1
                  if r["dataset"] == dataset
                  and not r["display"].startswith("fastPLS")
                  and r["display"] not in python_displays
                  and math.isfinite(number(r["time_sec"]))]
    ikpls = [number(r["time_sec"]) for r in fig1
             if r["dataset"] == dataset and r["display"] == "IKPLS"
             and math.isfinite(number(r["time_sec"]))]
    if dataset in ordinary_datasets and external_r and ftime <= min(external_r) * 1.000001:
        fastest_r_or_tied += 1
    if dataset in ordinary_datasets and external_r:
        r_comparable_count += 1
        workflow_speedups[dataset] = min(external_r) / ftime
    if ikpls:
        ikpls_comparable_count += 1
        ikpls_speedups[dataset] = min(ikpls) / ftime
        if ftime <= min(ikpls) * 1.000001:
            fastest_ikpls_or_tied += 1

nmr = {r["implementation"]: r for r in fig3}
decision = {r["family"]: r for r in nmr_decision}
cuda_faster = sum(number(r["ratio"]) > 1 for r in fig2 if r["platform"] == "CUDA")
metal_faster = sum(number(r["ratio"]) > 1 for r in fig2 if r["platform"] == "Metal")
cuda_comparisons = sum(r["platform"] == "CUDA" for r in fig2)
metal_comparisons = sum(r["platform"] == "Metal" for r in fig2)
cuda_lower_host_increment = sum(number(r["memory_ratio"]) < 1 for r in fig2
                                if r["platform"] == "CUDA")
metal_lower_host_increment = sum(number(r["memory_ratio"]) < 1 for r in fig2
                                 if r["platform"] == "Metal")
image_table = TAB / "figure4_imagenet_current.csv"
image_figure = FIG / "figure4_imagenet_current.png"
has_imagenet = image_table.exists() and image_figure.exists()
image = rows("figure4_imagenet_current.csv") if has_imagenet else []

rsvd_speedups = [number(r["speedup"]) for r in solver_paired]
rsvd_metric_differences = [number(r["metric_difference"]) for r in solver_paired]
precision_groups = {}
for row in precision:
    key = (row["dataset"], row["method"], row["backend"])
    precision_groups.setdefault(key, {})[row["precision"]] = row
precision_pairs = [value for value in precision_groups.values()
                   if "float32" in value and "float64" in value]
precision_memory_lower = sum(
    number(pair["float32"]["median_incremental_peak_rss_mib"]) <
    number(pair["float64"]["median_incremental_peak_rss_mib"])
    for pair in precision_pairs
)
precision_runtime_faster = sum(
    number(pair["float32"]["median_total_sec"]) <
    number(pair["float64"]["median_total_sec"])
    for pair in precision_pairs
)
precision_metric_max = max(
    abs(number(pair["float32"]["median_metric"]) -
        number(pair["float64"]["median_metric"]))
    for pair in precision_pairs
)
python_completed_configs = len(python_panel)
python_failed_configs = len({
    (row.get("dataset", ""), row.get("implementation", ""))
    for row in python_status
    if row.get("status") not in {"success", "not_repeated_long_runtime"}
})
python_by_key = {
    (row.get("dataset", ""), row.get("implementation", "")): row
    for row in python_panel
}
python_labels = {
    "nirs4all_methods_simpls": "nirs4all-methods SIMPLS",
    "nirs4all_methods_rsvd": "nirs4all-methods randomized-SVD PLS",
    "sklearn_plsregression": "scikit-learn PLSRegression",
}
cifar_fast = next(
    (row for row in fig1
     if row.get("dataset") == "cifar100"
     and row.get("display") == "fastPLS SIMPLS / argmax"),
    None,
)
cifar_sklearn = python_by_key.get(("cifar100", "sklearn_plsregression"))
cifar_nirs_rsvd = python_by_key.get(("cifar100", "nirs4all_methods_rsvd"))


title = "fastPLS: accelerated SIMPLS for high-dimensional biomedical data with optional CUDA and Metal routes"
main = Document()
configure(main)
set_core_properties(main, title, "Manuscript for Computer Methods and Programs in Biomedicine")
main.add_heading(title, 0)
paragraph(main, "Dupe Ojo¹*, Alessia Vignoli²*, Stefano Cacciatore¹†, Leonardo Tenori²˒³†")
paragraph(main, "¹ Bioinformatics Unit, International Centre for Genetic Engineering and Biotechnology, Cape Town, South Africa. ² Department of Experimental and Clinical Medicine, University of Florence, Florence, Italy. ³ Magnetic Resonance Center, University of Florence, Florence, Italy.")
paragraph(main, "* Equal contributions. † Co-corresponding authors: Stefano Cacciatore (stefano.cacciatore@icgeb.org) and Leonardo Tenori.")

heading(main, "Abstract")
paragraph(main, "Background and objective: Partial least-squares (PLS) models are valuable for biomedical data with correlated predictors and multivariate responses, but repeated component extraction and dense prediction paths can become computationally limiting. We developed fastPLS around an accelerated execution of the sequential SIMPLS algorithm.")
paragraph(main, "Methods: We evaluated fastPLS 0.99.65, which combines compiled sequential component updates, reusable deflation products, sample-space Gram updates for response-wide problems, compact latent prediction, label-aware class products and randomized singular value decomposition (rSVD). The package also implements PLS-SVD, orthogonal PLS (OPLS) and kernel PLS. Numerical routes include compiled CPU execution, fully device-resident NVIDIA CUDA float32/float64 execution and a fixed CPU/Metal operation split for Apple silicon in float32. Standard R matrices use float64, whereas float-package matrices select float32. Benchmarks measured prediction, fitting-plus-prediction time and process memory on biomedical and controlled matrix regimes.")
abstract_results = f"Results: In the one-CPU comparison, the faster current fastPLS workflow was faster than or tied with the fastest completed independent R workflow on {fastest_r_or_tied} of {r_comparable_count} ordinary classification and regression datasets and faster than or tied with float32 IKPLS on {fastest_ikpls_or_tied} of {ikpls_comparable_count} completed paired datasets; predictive metrics are reported alongside each timing rather than inferred from speed. ImageNet/DINOv2 was retained as a single-run 1,000-component boundary stress test, with methods not executed at this scale shown as not evaluated. In controlled matched calculations, rSVD was {min(rsvd_speedups):.1f}- to {max(rsvd_speedups):.1f}-fold faster than the IRLBA companion across balanced, predictor-wide and response-wide matrices; RMSD differences were at most {scientific(max(rsvd_metric_differences))}. Verified four-thread OpenBLAS execution provided 1.03- to 1.77-fold speed-up, depending on matrix shape."
abstract_results += (
    f" At a common 165-component NMR workload, matched Linux SIMPLS "
    f"required {fmt(nmr['SIMPLS / CPU']['total_time_sec'], 3)} s "
    f"on CPU and {fmt(nmr['SIMPLS / CUDA']['total_time_sec'], 3)} s on "
    f"CUDA. The Apple CPU/Metal route completed the same float32 SIMPLS "
    f"calculation in {fmt(nmr['SIMPLS / Metal']['total_time_sec'], 3)} s; "
    f"cross-platform timings were not interpreted as hardware speed ratios."
)
paragraph(main, abstract_results)
paragraph(main, "Conclusions: fastPLS extends sequential PLS computation to matrix regimes that are difficult to process through conventional R workflows. Its gains arise from the combined execution and storage strategy rather than from a universally faster individual optimization. rSVD remains approximate, and precision, CPU threading and accelerator use should be selected according to numerical agreement and matrix shape.")
paragraph(main, "Keywords: partial least squares; SIMPLS; randomized singular value decomposition; GPU computing; NMR; omics")

heading(main, "1. Introduction")
paragraph(main, "Partial least squares (PLS) constructs latent components that maximize predictor-response association and is widely used when biomedical measurements are numerous, collinear or larger in number than the available samples [1]. PLS has supported metabolomic classification and prediction, including analyses of inflammatory metabolic phenotypes in prostate cancer [2]. It can also serve as supervised feature extraction: the latent scores retain response-relevant structure before a downstream classifier or retrieval method is applied.")
paragraph(main, "Several PLS formulations address different computational and statistical settings. PLS-SVD derives directions from a singular value decomposition of the predictor-response cross-covariance, whereas SIMPLS extracts sequential components while preserving a deflation geometry in the original variable space [3]. Orthogonal PLS separates response-orthogonal variation [4], and kernel PLS permits nonlinear relations through a kernel representation [5]. The R package pls provides established implementations [6], while IKPLS supplies NumPy- and JAX-based improved-kernel PLS algorithms for CPU and GPU computation [7]. Python alternatives include the widely used scikit-learn PLSRegression estimator [17] and the compiled multi-solver nirs4all-methods engine [18].")
paragraph(main, "For large matrices, the dominant directions can be approximated without a complete singular value decomposition. Randomized SVD (rSVD) constructs a low-dimensional range approximation and can replace expensive dense decompositions when the leading subspace is sufficiently separated [8]. Its approximation depends on rank, oversampling, power iterations, conditioning and seed; therefore, computational gains must be interpreted together with numerical diagnostics.")
paragraph(main, "Multivariate spectral prediction provides a demanding biomedical example. The deposited workflow associated with a recent NMR study predicted 28,355 diffusion-edited spectral intensities from 13,000 NOESY bins in 1,200 training spectra [9]. That implementation used PLS-SVD with an iterative Lanczos bidiagonalization solver and 165 components on its original workstation. The response dimension makes both fitting and prediction expensive, motivating a sequential SIMPLS implementation that approaches one-shot PLS-SVD execution while retaining the ability to construct many components.")
paragraph(main, "Large embedding matrices create a related computational regime after feature extraction. Foundation models such as UNI and Prov-GigaPath produce dense representations for downstream computational pathology analyses [13,14]. We therefore include DINOv2 embeddings [10] derived from ImageNet [16] as an engineering stress test of million-sample matrix processing, not as evidence of biomedical predictive validity.")
paragraph(main, "We present fastPLS, a Bioconductor R package centred on accelerated SIMPLS execution. Its contribution is not the component-path concept already available in conventional SIMPLS software, but the combination of compiled sequential updates, reusable products and persistent workspaces, sample-space Gram updates for response-wide problems, compact prediction, label-aware class products, matrix-free operators and corresponding CPU, CUDA and Metal implementations. PLS-SVD, OPLS, kernel PLS, argmax decoding, latent-space linear discriminant analysis (LDA) and compiled cross-validation share the same public interface.")

heading(main, "2. Materials and methods")
heading(main, "2.1 PLS algorithms and numerical execution", 2)
paragraph(main, "Let X be an n by p centred predictor matrix and Y an n by q centred response matrix. The cross-covariance is S = XᵀY. An explicit route materializes S; an implicit route applies SΩ = Xᵀ(YΩ) and SᵀQ = Yᵀ(XQ) without retaining the p by q matrix. The implicit route reduces storage when p q is large, but repeated passes through X and Y can be slower when S fits comfortably in memory.")
paragraph(main, "PLS-SVD approximates S once as UDVᵀ. Scores T = XU and their Gram matrix TᵀT are reused across requested component prefixes, and held-out predictions are formed through latent factors instead of a dense coefficient cube. The attainable number of components is limited by the numerical rank of S and therefore by the response rank.")
paragraph(main, "SIMPLS follows de Jong's sequential orthogonalization and deflation geometry [3]. fastPLS keeps score, loading and deflation workspaces, computes each deflation row once, uses matrix-matrix operations where eligible, updates requested prediction prefixes incrementally and avoids storing fitted responses unless requested. The component-wise route obtains each direction from a fresh randomized sketch of the current deflated cross-covariance. For eligible large multiclass or response-wide problems, CPU, CUDA and Metal routes can instead obtain a small independent candidate block from the current deflated state and consume those candidates sequentially through the SIMPLS orthogonalization and deflation updates. This faster block execution is an approximate SIMPLS variant and is not claimed to reproduce a fresh dominant-direction solve at every component.")

add_table(main, "Algorithm 1. Accelerated SIMPLS execution.", ["Step", "Operation"], [
    ["1", "Centre or scale X with training statistics and centre Y; form S = XᵀY or define its implicit products."],
    ["2", "Initialize R, Q, V and optional score/output workspaces. Cache XᵀX only in the eligible p <= n regime; cache G = SᵀS when q <= p and q <= 512."],
    ["3", "At component a, sketch the current S (or its implicit products). Use one candidate by default; eligible large multiclass or response-wide CPU, CUDA and Metal routes may return a bounded candidate block."],
    ["4", "For each candidate r in the block, orthogonalize r against retained score/weight state, form t = Xr and normalize t and r."],
    ["5", "Compute p = Xᵀt and q = Yᵀt. Label-aware classification obtains q from class sums without constructing dense one-hot Y."],
    ["6", "Orthogonalize p against V to obtain v. Compute the deflation row h = vᵀS once, update S <- S - vh, and update G by the corresponding rank-one term when G is cached."],
    ["7", "Append r, q, v and optional t. Increment coefficient, fitted-value and metric paths only when their requested component prefixes are reached."],
    ["8", "After the block is consumed, resketch the newly deflated operator. Predict by applying training preprocessing, forming Xnew R, and multiplying by the compact response factors."],
], font_size=7.6)

add_table(main, "Algorithm 2. Compact PLS-SVD execution.", ["Step", "Operation"], [
    ["1", "Centre or scale X and centre Y. For classification, compute S = XᵀY from class sums without materializing a dense dummy-response matrix."],
    ["2", "Compute one rank-A randomized decomposition S approximately equal to U D Vᵀ, explicitly or through the matrix-free products S Omega = Xᵀ(Y Omega) and SᵀQ = Yᵀ(XQ)."],
    ["3", "Form the complete retained score matrix T = XU once and cache H = TᵀT."],
    ["4", "For each requested component count a, solve H[1:a,1:a] C_a = D[1:a,1:a] without matrix inversion."],
    ["5", "Store the compact response map W_a = C_a V_aᵀ; materialize the dense coefficient matrix U_a W_a or fitted values only when requested."],
    ["6", "Predict held-out samples as Ynew = Xnew U_a W_a plus the training-response mean."],
], font_size=7.6)

paragraph(main, "OPLS applies response-orthogonal filtering before fitting the predictive PLS core [4]. Kernel PLS uses a linear shortcut for the linear kernel and an explicitly centred Gram matrix for polynomial and radial-basis kernels [5]. The nonlinear route therefore requires O(n²) storage and is intended for sample sizes whose Gram matrix and working copies fit the available host memory.")

heading(main, "2.2 rSVD and computational backends", 2)
paragraph(main, "The public low-rank solver is rSVD. Automatic controls use profile-specific oversampling and power iterations: the ordinary profile uses 32 and 5, high-response and sparse-high-class profiles use 48/6 or 64/7, and the massive-cross-covariance SIMPLS profile uses 12/1. The effective controls, seed, executed estimator and numerical status are retained internally for diagnostics. Approximate results are not described as exact equivalence to a dense decomposition.")
paragraph(main, "CPU routes are compiled C++ and call the linked BLAS/LAPACK; multicore execution is available only when the linked numerical library and operation use multiple threads. CUDA routes use NVIDIA cuBLAS, cuSOLVER and cuRAND for device matrix products, factorizations and randomized sketches [11]. After input transfer, CUDA retains preprocessing, decomposition, SIMPLS updates, OPLS filtering, nonlinear-kernel construction and centering, prediction and LDA on the device in float32 and float64. The Apple route instead uses a fixed operation split: persistent Metal Performance Shaders and custom kernels evaluate fitting products involving the training sample matrix, whereas the CPU performs centering and scaling, reduced QR/SVD calculations, sequential orthogonalization and deflation, coefficient assembly, LDA and compact prediction [12]. This assignment is invariant to dataset shape. Metal accepts float32 because the tested Apple GPU does not provide the float64 arithmetic required by the kernels. Unsupported accelerator or precision combinations return an error rather than silently falling back to CPU.")
paragraph(main, "The Metal installation step compiles and embeds the custom kernel library when the Apple Metal compiler is available; runtime compilation remains a portability fallback. Device and pipeline initialization is incurred by the first accelerated product and reused within a session. This operation split deliberately avoids placing the sequential SIMPLS state machine on the GPU: broad sample-matrix products expose useful parallelism, whereas the smaller, dependency-heavy component updates remain with Apple Accelerate on the CPU. Fresh-process timings include Metal initialization.")
paragraph(main, "R stores ordinary numeric matrices in float64. Inputs created with the float package occupy float32 storage and automatically select a supported float32 numerical route. This can reduce the size of input and intermediate arrays, but complete-process memory and runtime also include the R session, loaded data, libraries, allocator state and device context. Precision comparisons consequently report measured memory and prediction differences rather than inferring a twofold process-memory reduction.")

heading(main, "2.3 Classification, regression and validation", 2)
paragraph(main, "For classification, argmax returns the largest predicted dummy-response score. LDA is fitted to retained PLS scores. The pooled within-class covariance is computed as [TᵀT − Σⱼ nⱼμⱼμⱼᵀ]/max(1,n−J), without materializing centred class blocks. Regularized systems are solved by Cholesky factorization and triangular solves. The deterministic scale-normalized fallback tests ρ = 10⁻⁸, 10⁻⁶, 10⁻⁵, 10⁻⁴, 10⁻³ and 10⁻² and uses the first successful factorization. The discriminant is δⱼ(t) = tᵀwⱼ − 0.5 μⱼᵀwⱼ + log(nⱼ/n).")
paragraph(main, "The compiled single and double cross-validation procedures preserve groups supplied through constrain, preventing observations from one subject from entering both training and validation folds. Component number and prediction-relevant model arguments can be selected using accuracy, balanced accuracy, RMSD or Q² as appropriate. Training R², independent-test Q² relative to the training mean and fold-based cross-validated Q² are returned as distinct quantities. Permutation p-values use the finite-sample correction (b + 1)/(B + 1); when groups are supplied, labels are permuted at the exchangeability-block level.")

heading(main, "2.4 Benchmark design and data", 2)
paragraph(main, "The classification comparison used CCLE, CIFAR-100 [15], GTEx v8, MetRef, Retina, Tabula Muris, TCGA-BRCA, TCGA-HNSC methylation and TCGA Pan-Cancer. CBMC CITE-seq and PRISM supplied multivariate regression workloads, and NMR was analysed separately. Dataset construction, preprocessing, dimensions, acquisition and redistribution restrictions are reported in Supplementary Tables S1 and S2. The same prepared train/test split, component count and precision were used within each paired comparison.")
paragraph(main, "The independent-implementation comparison used an Ubuntu 22.04 Linux workstation with an Intel Core i7-13700 processor and 32 GiB RAM. Every implementation used one effective CPU thread. The fastPLS 0.99.65 build was linked directly to OpenBLAS 0.3.29 and fitted SIMPLS with rSVD to centred float32 predictors. Component counts were fixed before this rerun from the training component-path analysis and are reported in Supplementary Table S11. The rSVD controls were oversampling 32, five power iterations and seed 123. Classification used latent-score LDA; regression returned continuous predictions and RMSD. Fitted responses, variance summaries and loading matrices were not requested; total time included fitting and held-out prediction. IKPLS used float32 and the same component count. R and Python implementations used the precision recorded for each workflow, and external classification scores were decoded by argmax where required. The comparison is therefore an end-to-end software comparison rather than an identical numerical-kernel comparison. Current fastPLS and IKPLS results for ordinary datasets are medians of ten isolated processes. ImageNet/DINOv2 used one run at 1,000 requested components, and other rows use the completed repetition count recorded in the source table. Complete-process resident set size (RSS), convergence failures and numerical warnings were retained.")
paragraph(main, "The backend comparison evaluated PLS-SVD, SIMPLS, OPLS and kernel PLS on 11 non-NMR datasets using family-specific component counts selected from training data. CPU/CUDA and CPU/Metal ratios are paired within each workstation; values above one favour the accelerator. CUDA timing includes host-to-device transfer, fitting, synchronization, prediction and result transfer. Absolute RSS is a feasibility measure. Incremental RSS subtracts the baseline immediately before fitting, but still measures the complete process; GPU increments may include context and allocator initialization.")
paragraph(main, "CPU thread scaling was evaluated separately with an OpenBLAS-linked build. Three controlled workloads represented sample-rich classification, predictor-wide regression and response-wide regression. One, two and four active OpenBLAS threads were verified directly before each fit, with five repetitions per setting and identical model controls.")
paragraph(main, "A supporting float32-versus-float64 comparison assessed runtime, prediction differences and baseline-corrected process RSS after precision conversion and is reported in Supplementary Table S9 and Figure S13.")
paragraph(main, "The effect of the low-rank solver was isolated in the companion benchmark by holding the simulated matrices, 20-component workload, preprocessing, family and prediction output constant. PLS-SVD and SIMPLS were compared with native rSVD and the IRLBA companion on balanced, predictor-wide and response-wide shapes in five isolated processes. This comparison evaluates solver cost within the same fastPLS execution design; IRLBA is not part of the public package.")
paragraph(main, "The NMR data comprised 1,200 training and 321 held-out spectra with 13,000 predictor bins and 28,355 response intensities. Predictor bins strictly between 4.6 and 4.8 ppm were set to zero in both training and test matrices as routine water-region preprocessing before model selection; response spectra were not masked, and all response columns entered the metrics. Five paired training-only splits were used. For each family, the smallest component count whose mean validation RMSD was no greater than the minimum mean plus its standard error was selected within the evaluated grid. Predictive selection and a separate fixed 165-component implementation comparison were not pooled.")
paragraph(main, "Numerical validation was separated from performance benchmarking. The deterministic component-wise SIMPLS route was compared with a dense reference across conditioned, collinear, rank-deficient, high-response, p<n and p>n cases. Public rSVD profiles were evaluated over repeated seeds on CPU, CUDA and Metal using predefined prediction, correlation, label-agreement and metric tolerances. OPLS and nonlinear kernel PLS were checked independently in deterministic float64 CPU execution. A same-code ablation disabled one optimization at a time to quantify its route-dependent contribution.")
paragraph(main, "Accuracy is the fraction of correct labels; balanced accuracy is the unweighted mean of class-specific recalls. RMSD is the square root of the mean squared response error. Independent-test Q² is 1 minus the prediction sum of squares divided by the sum of squared deviations from the training-response mean. Top-5 accuracy is the fraction for which the observed class is among the five largest predicted class scores. Timing summaries report medians and interquartile ranges where repeated measurements are available.")

heading(main, "3. Results")
heading(main, "3.1 Comparison with independent implementations", 2)
largest_speedups = sorted(workflow_speedups.items(), key=lambda item: item[1], reverse=True)[:3]
speedup_text = "; ".join(f"{dataset}, {value:.2f}-fold" for dataset, value in largest_speedups)
paragraph(main, f"Across the ordinary classification and regression datasets, the fastPLS SIMPLS workflow was faster than or tied with the fastest completed R implementation on {fastest_r_or_tied} of {r_comparable_count} datasets (Figure 1). Classification used latent-score LDA and regression used continuous SIMPLS prediction. fastPLS used centred float32 predictors, the fixed component contract in Supplementary Table S11, oversampling 32, five power iterations, seed 123 and one CPU thread. The three largest ratios relative to the fastest completed R implementation were {speedup_text}. In the float32 comparison with IKPLS, fastPLS was faster than or tied on {fastest_ikpls_or_tied} of {ikpls_comparable_count} completed paired datasets. The single-run ImageNet/DINOv2 row uses 1,000 requested components as a boundary stress test; implementations not executed at that scale remain marked NE rather than being omitted or labelled as failures.")
imagenet_simpls_lda = next(
    (row for row in fig1 if row.get("dataset") == "imagenet" and
     row.get("display") == "fastPLS SIMPLS / LDA"), None
)
imagenet_ikpls = next(
    (row for row in fig1 if row.get("dataset") == "imagenet" and
     row.get("display") == "IKPLS"), None
)
if imagenet_simpls_lda and imagenet_ikpls:
    paragraph(
        main,
        "At the ImageNet boundary workload, the fastPLS SIMPLS-LDA workflow "
        f"completed fitting and prediction in {fmt(imagenet_simpls_lda['time_sec'], 1)} s "
        f"with accuracy {fmt(imagenet_simpls_lda['accuracy'], 5)}, versus "
        f"{fmt(imagenet_ikpls['time_sec'], 1)} s and {fmt(imagenet_ikpls['accuracy'], 5)} "
        "for IKPLS at the same 1,000-component request. These "
        "single-run values characterize computational feasibility rather than "
        "biomedical predictive utility."
    )
if python_panel or python_status:
    paragraph(main, f"The Python extension evaluated scikit-learn under the same split, component and one-thread contract. It produced {python_completed_configs} completed method-dataset configurations and {python_failed_configs} configurations with retained failures (Supplementary Table S17).")
if cifar_fast and cifar_sklearn:
    cifar_text = (
        f"At the matched {int(number(cifar_fast['ncomp']))}-component CIFAR-100 "
        f"workload, scikit-learn required {fmt(cifar_sklearn['median_total_sec'], 1)} s "
        f"and achieved accuracy {fmt(cifar_sklearn['accuracy'], 4)}, whereas fastPLS "
        f"required {fmt(cifar_fast['time_sec'], 3)} s and achieved accuracy "
        f"{fmt(cifar_fast['accuracy'], 4)}."
    )
    paragraph(main, cifar_text)
paragraph(main, "These end-to-end comparisons used the same prepared split, response encoding, component count and one-thread execution contract within each applicable method comparison. The requested component count was shared by fastPLS SIMPLS, IKPLS and the independent implementations. Per-dataset component counts are reported in Supplementary Table S11; implementation precision, solver, retained outputs, repetition counts and numerical status are reported in Supplementary Table S17.")
paragraph(main, "The timing crossover was associated with workload scale rather than a uniform implementation ranking. These end-to-end timings include language-interface and output-object construction. For sub-second R workflows, validation, allocation and assembly of R matrices and model lists can represent a larger fraction of elapsed time than the corresponding NumPy-array assembly in Python. IKPLS therefore retained lower latency for several small or low-p tasks in which fixed overhead was comparable to the numerical work, whereas the compiled fastPLS paths became advantageous as the retained component path, sample count or response dimension increased. The reported ratios compare complete software workflows rather than isolated numerical kernels and do not imply that one implementation is fastest for every matrix shape.")
add_landscape_figure(main, "figure1_independent_implementations.png", "Figure 1. Single-CPU PLS prediction workflows measured on the same Ubuntu 22.04 Intel Core i7-13700 workstation. The single fastPLS row represents SIMPLS-rSVD with LDA for classification and SIMPLS-rSVD regression for continuous responses. fastPLS 0.99.65 used an OpenBLAS-linked build, one CPU thread and float32 inputs. Package names are shown once at the left; the regression panels use the same row order, and every dataset column has the same width. Panels A and B report held-out classification accuracy and regression RMSD, panels C and D report fitting-plus-prediction time on a common logarithmic seconds scale, and panels E and F report absolute peak process RSS on a common logarithmic MiB scale. Values are medians of repeated isolated processes where available; ImageNet/DINOv2 is a single-run 1,000-component boundary stress test. Component counts and execution details are reported in Supplementary Tables S11 and S17. Failed denotes an attempted calculation that did not complete; NE denotes not evaluated.")
paragraph(main, "Separate numerical checks supported interpretation of these timing results. Component-wise SIMPLS was evaluated against a dense numerical reference across classification, regression, collinear and rank-deficient cases. OPLS and polynomial and radial-basis kernel PLS were checked independently. These tests establish agreement within the evaluated conditions, not universal exactness of randomized routes (Supplementary Table S4). The same-code ablation confirmed that individual execution optimizations can help or hurt according to matrix shape (Supplementary Table S5).")

heading(main, "3.2 Solver and backend execution", 2)
paragraph(main, f"In the matched controlled solver experiment, rSVD was {min(rsvd_speedups):.1f}- to {max(rsvd_speedups):.1f}-fold faster than the IRLBA companion across PLS-SVD and SIMPLS. The largest absolute RMSD difference was {scientific(max(rsvd_metric_differences))}. Median incremental host RSS was lower with rSVD in five of six comparisons; response-wide SIMPLS was the exception (Supplementary Table S10 and Figure S14).")
backend_text = f"Accelerator benefit was conditional on matrix shape, model family and execution context (Figure 2). CUDA was faster than the paired CPU run in {cuda_faster} of {cuda_comparisons} fresh-process comparisons, with the clearest gains for larger dense products. The public Apple backend used the same fixed CPU/Metal operation split for every dataset: Metal evaluated fitting products involving the training sample matrix, while the CPU completed reduced decompositions, sequential PLS updates and compact prediction. It was faster than the paired Mac CPU run in {metal_faster} of {metal_comparisons} fresh-process comparisons. Incremental host RSS was lower than the paired CPU measurement in {cuda_lower_host_increment} CUDA and {metal_lower_host_increment} Metal comparisons."
backend_text += " Every completed timing is shown, regardless of numerical agreement; Supplementary Tables S7 and S8 report paired metrics, host-memory measurements, CUDA device memory and executed residency."
paragraph(main, backend_text)
paragraph(main, "Verified four-thread CPU execution produced 1.21-fold, 1.03-fold and 1.77-fold speed-ups for the sample-rich, predictor-wide and response-wide controlled workloads, respectively, with identical predictions across thread counts (Supplementary Table S15 and Figure S15). Thus, a multithreaded build can accelerate matrix-heavy routes, but the sequential SIMPLS updates and workload balance limit scaling.")
add_figure(main, "figure2_backend_runtime.png", "Figure 2. Paired CPU/accelerator runtime and incremental host-memory ratios for all selected family-dataset workloads. Runtime values are CPU time divided by CUDA or the fixed CPU/Metal operation split, so values above one favour the accelerator. Memory values are accelerator divided by CPU incremental host RSS, so values below one favour the accelerator. Fresh-process rows include device and pipeline initialization. Ratios are paired within each workstation; CUDA and Metal computers are not compared directly. Numerical differences and execution residency are reported in Supplementary Tables S7 and S8.", 6.65)

heading(main, "3.3 Multivariate NMR prediction", 2)
paragraph(main, f"The training-only one-standard-error rule selected {decision['plssvd']['selected_ncomp']} PLS-SVD components and {decision['simpls']['selected_ncomp']} SIMPLS components within grids extending to {decision['simpls']['largest_tested_ncomp']} components (Supplementary Figure S12). The PLS-SVD mean validation minimum occurred at {decision['plssvd']['minimum_mean_ncomp']} components, with {decision['plssvd']['eligible_ncomp']} eligible under the one-standard-error threshold. SIMPLS reached its mean minimum at {decision['simpls']['minimum_mean_ncomp']} components, with {decision['simpls']['eligible_ncomp']} eligible. These values are selections within the evaluated grids rather than unconstrained optima.")
paragraph(main, f"At the common 165-component workload, float32 PLS-SVD required {fmt(nmr['PLS-SVD / CPU']['total_time_sec'], 3)} s on the Linux CPU, {fmt(nmr['PLS-SVD / CUDA']['total_time_sec'], 3)} s on CUDA and {fmt(nmr['PLS-SVD / Metal']['total_time_sec'], 3)} s through the Apple CPU/Metal route. The corresponding SIMPLS times were {fmt(nmr['SIMPLS / CPU']['total_time_sec'], 3)}, {fmt(nmr['SIMPLS / CUDA']['total_time_sec'], 3)} and {fmt(nmr['SIMPLS / Metal']['total_time_sec'], 3)} s. CPU and CUDA were measured on the same Intel/NVIDIA workstation, giving a {number(nmr['SIMPLS / CPU']['total_time_sec']) / number(nmr['SIMPLS / CUDA']['total_time_sec']):.1f}-fold SIMPLS runtime ratio. Metal was measured on the Apple M3 and is therefore reported as a separate implementation result rather than a direct ratio to the Linux CPU. All six routes used the same prepared split, float32 inputs, rSVD controls, seed and component count.")
nmr_python_success = [
    row for row in python_large
    if row.get("dataset") == "nmr" and row.get("status") == "success"
]
nmr_python_failed = [
    row for row in python_large
    if row.get("dataset") == "nmr" and row.get("status") != "success"
]
if nmr_python_success or nmr_python_failed:
    statements = []
    for row in nmr_python_success:
        label = row.get("algorithm") or python_labels.get(
            row.get("implementation", ""), row.get("implementation", "Python PLS")
        )
        statements.append(
            f"{label} completed in {fmt(row.get('total_sec'), 1)} s with "
            f"RMSD {fmt(row.get('rmsd'), 6)} and peak RSS "
            f"{fmt(row.get('peak_rss_mib'), 0)} MiB"
        )
    for row in nmr_python_failed:
        label = row.get("algorithm") or python_labels.get(
            row.get("implementation", ""), row.get("implementation", "Python PLS")
        )
        statements.append(f"{label} did not complete")
    paragraph(
        main,
        "A separate 50-component, native-float64 Python feasibility comparison "
        + "; ".join(statements)
        + " (Supplementary Table S17). These rows are not pooled with the "
          "165-component implementation comparison.",
    )
paragraph(main, "The per-spectrum RMSD distribution showed that most held-out spectra clustered near the global error, with a limited upper tail. The displayed spectrum was selected as the held-out sample nearest the median current CPU SIMPLS per-spectrum RMSD. Both the full 12–0 ppm range and the 1.7–0.5 ppm expansion show the agreement of predicted and observed spectral structure. The water interval was removed from predictors only; it remained part of the unmasked response evaluation.")
add_figure(main, "figure3_nmr_fixed165.png", "Figure 3. NMR prediction at a common 165 components. PLS-SVD and SIMPLS are shown for CPU, CUDA and Metal only. Panels compare median fitting-plus-prediction time with interquartile range over three isolated processes, held-out RMSD, incremental process RSS, per-spectrum RMSD and observed/predicted spectra for the held-out sample nearest the median CPU SIMPLS error. The runtime axis begins at zero. CPU and CUDA were measured on the Intel/NVIDIA workstation, whereas Metal was measured on the Apple M3; cross-platform timings are not interpreted as hardware speed ratios. Input conversion is excluded, accelerator initialization and transfer are included, and all 28,355 response variables contribute to the metrics.", 6.65)

heading(main, "3.4 Foundation-model embedding stress test", 2)
if has_imagenet:
    paragraph(main, "The ImageNet/DINOv2 experiment fitted float32 SIMPLS on 1,000,000 training embeddings and evaluated 281,167 held-out embeddings over 50–1,000 requested components with argmax and LDA. Figure 4 reports top-1 and top-5 accuracy, total fitting and prediction time, and observed post-prediction host and device memory. These single-run values are exploratory; the noncanonical split and incomplete extraction provenance preclude a confirmatory predictive claim, and 1,000 components is a boundary stress point rather than an optimum.")
    add_figure(main, "figure4_imagenet_current.png", "Figure 4. Exploratory current-release ImageNet/DINOv2 float32 SIMPLS stress test. Argmax and LDA are evaluated over 50–1,000 components on 1,000,000 training and 281,167 held-out embeddings. Timing includes fitting and held-out prediction. Memory is the observed post-prediction process RSS and device allocation, not a sampled peak. Results are single-run feasibility measurements, not biomedical validation.", 6.65)
else:
    paragraph(main, "A current-release ImageNet/DINOv2 rerun is in progress. No result from an earlier package execution path is included in this draft. The final analysis will report argmax and LDA over 50–1,000 components, including fitting, held-out prediction, top-1 and top-5 accuracy, host RSS, GPU memory and route residency.")

heading(main, "4. Discussion")
paragraph(main, "fastPLS accelerates SIMPLS through execution and storage choices rather than redefining the underlying sequential PLS objective. Reusing deflation products and workspaces reduces repeated allocation, while compact latent prediction avoids dense p by q coefficient arrays for every requested prefix. Label-aware products are particularly helpful in multiclass problems because the response cross-product can be formed from class sums without materializing a dense n by J indicator matrix. These gains explain why the current single-CPU workflow was fastest or tied on most completed classification datasets, while the remaining small task showed that package overhead can dominate when all methods finish in hundredths of a second.")
paragraph(main, "The choice between PLS-SVD and SIMPLS depends on the scientific and matrix regime. PLS-SVD obtains a retained subspace in one decomposition and was faster for the extreme-response NMR workload, but its component count is response-rank limited. SIMPLS pays for sequential orthogonalization and deflation, yet can continue beyond a low response rank and supports an interpretable component path. Compact prediction matters most when p, q, the test size or the number of requested prefixes makes dense prediction storage large. Matrix-free cross-covariance is valuable when p q storage is prohibitive; otherwise, materializing S can be faster because it avoids repeated passes through X and Y.")
paragraph(main, "rSVD is retained as the primary solver because it enables the observed large-scale execution, but it is an approximation rather than an exact replacement for every spectrum or conditioning regime. Automatic profiles increase oversampling and power iterations outside the massive-cross-covariance route, and the fit records the effective settings and numerical status. Users conducting confirmatory biomedical analyses should examine stability across seeds and compare predictions or selected components when the singular spectrum is poorly separated. Reaching a component-grid boundary should trigger extension of the training-only grid or cautious reporting as the best tested value.")
paragraph(main, "GPU use is not automatically advantageous. CUDA became useful when dense products or response dimensions were large enough to amortize transfer and context costs; matched NMR SIMPLS was substantially faster on CUDA than on the paired Linux CPU, while most small tasks remained CPU-favourable. On Apple silicon, full device residency was not retained because sequential reduced decompositions and component updates were more efficient through Apple Accelerate. The public Metal route therefore assigns fitting products involving the training sample matrix to persistent Metal workspaces and keeps reduced factorizations, sequential orthogonalization, deflation, coefficient assembly, LDA and compact prediction on the CPU. This operation assignment is fixed across datasets and preserves the same PLS calculation; it is not a shape-based choice of whole-model backend. CUDA OPLS and nonlinear-kernel routes remain device-native in float32 and float64; Metal routes use the documented CPU/Metal split in float32. Unsupported accelerator requests return an error rather than invoking a hidden CPU fallback. Nonlinear kernels remain practically limited by O(n²) Gram-matrix storage.")
paragraph(main, "float32 reduces the representation size of input and many intermediates, which was essential for the million-row and extreme-response workflows, but it is not a universal speed or process-memory guarantee. The current NMR results show small route-dependent metric differences, and complete-process RSS includes data, runtime libraries and allocator state. Precision should therefore be selected according to feasibility and verified numerical behaviour rather than assumed superiority.")
paragraph(main, "The study has limitations. Fixed prepared splits primarily support paired computational comparison and do not replace subject-grouped external validation. The broad independent-software panel is an end-to-end workflow comparison with different native precisions and model objects. Accelerator ratios depend on two workstations and include initialization overhead. The ImageNet experiment is an engineering analogue for foundation-model embeddings, not biomedical evidence. Future work will expand validation on other GPU architectures, strengthen route-specific numerical diagnostics and refine automatic dispatch using controlled multi-factor scaling experiments.")

heading(main, "5. Conclusions")
paragraph(main, "fastPLS combines a compiled sequential SIMPLS path with compact prediction, rSVD and optional CUDA and Metal execution. It extends practical PLS analysis to response and sample dimensions that were previously difficult to process in R, while preserving explicit reporting of precision, backend residency and numerical controls. The NMR application demonstrates the value of the implementation for high-response biomedical prediction; appropriate solver and backend choices remain workload dependent.")

heading(main, "Declarations")
paragraph(main, "Acknowledgements: The authors thank the University of Cape Town's ICTS High Performance Computing team for providing a high-performance computing facility for this study (https://ucthpc.uct.ac.za/).")
paragraph(main, "Funding: This research received no specific grant from funding agencies in the public, commercial or not-for-profit sectors.")
paragraph(main, "Competing interests: The authors declare no competing financial interests or personal relationships that could have influenced this work.")
paragraph(main, "Data and software availability: fastPLS is available through Bioconductor and at https://github.com/tkcaccia/fastPLS. Executable benchmark and figure-generation scripts are maintained separately at https://github.com/tkcaccia/fastPLS-extra; the frozen publication archive will include the result tables and restricted-data acquisition instructions. Public datasets remain subject to their source licences and access conditions.")

heading(main, "References")
references = [
    "[1] Wold S, Sjöström M, Eriksson L. PLS-regression: a basic tool of chemometrics. Chemometrics and Intelligent Laboratory Systems. 2001;58:109–130.",
    "[2] Cacciatore S, Wium M, Licari C, et al. Inflammatory metabolic profile of South African patients with prostate cancer. Cancer & Metabolism. 2021;9:29. doi:10.1186/s40170-021-00265-6.",
    "[3] de Jong S. SIMPLS: an alternative approach to partial least squares regression. Chemometrics and Intelligent Laboratory Systems. 1993;18:251–263.",
    "[4] Trygg J, Wold S. Orthogonal projections to latent structures (O-PLS). Journal of Chemometrics. 2002;16:119–128.",
    "[5] Rosipal R, Trejo LJ. Kernel partial least squares regression in reproducing kernel Hilbert space. Journal of Machine Learning Research. 2001;2:97–123.",
    "[6] Mevik B-H, Wehrens R. The pls package: principal component and partial least squares regression in R. Journal of Statistical Software. 2007;18:1–23.",
    "[7] Andersson CA. IKPLS: fast improved kernel partial least squares algorithms. Journal of Open Source Software. 2024;9:6533. doi:10.21105/joss.06533.",
    "[8] Halko N, Martinsson P-G, Tropp JA. Finding structure with randomness: probabilistic algorithms for constructing approximate matrix decompositions. SIAM Review. 2011;53:217–288.",
    "[9] Vignoli A, et al. Multivariate prediction of diffusion-edited NMR spectra from NOESY data. Nature Communications. 2025. doi:10.1038/s41467-025-65294-x.",
    "[10] Oquab M, Darcet T, Moutakanni T, et al. DINOv2: learning robust visual features without supervision. Transactions on Machine Learning Research. 2024.",
    "[11] NVIDIA Corporation. CUDA Toolkit documentation: cuBLAS, cuSOLVER and cuRAND libraries. https://docs.nvidia.com/cuda/.",
    "[12] Apple Inc. Metal Performance Shaders documentation. https://developer.apple.com/metal/Metal-Performance-Shaders/.",
    "[13] Chen RJ, Ding T, Lu MY, et al. Towards a general-purpose foundation model for computational pathology. Nature Medicine. 2024;30:850–862. doi:10.1038/s41591-024-02857-3.",
    "[14] Xu H, Usuyama N, Bagga J, et al. A whole-slide foundation model for digital pathology from real-world data. Nature. 2024;630:181–188. doi:10.1038/s41586-024-07441-w.",
    "[15] Krizhevsky A, Hinton G. Learning multiple layers of features from tiny images. Technical report. University of Toronto; 2009.",
    "[16] Deng J, Dong W, Socher R, Li LJ, Li K, Fei-Fei L. ImageNet: a large-scale hierarchical image database. IEEE Conference on Computer Vision and Pattern Recognition. 2009:248–255. doi:10.1109/CVPR.2009.5206848.",
    "[17] Pedregosa F, Varoquaux G, Gramfort A, et al. Scikit-learn: machine learning in Python. Journal of Machine Learning Research. 2011;12:2825–2830.",
    "[18] Beurier G. nirs4all-methods: portable C++17 partial least-squares methods engine, version 1.0.18. 2026. https://methods.nirs4all.org/.",
]
for ref in references:
    paragraph(main, ref)


supp = Document()
configure(supp, supplement=True)
set_core_properties(supp, "Supplementary material: " + title,
                    "Supplementary methods, tables and figures")
supp.add_heading("Supplementary material", 0)
paragraph(supp, title)

heading(supp, "S1. Dataset construction and preprocessing")
paragraph(supp, "All paired computational comparisons used prepared training and test objects. Preprocessing parameters were estimated from training data and applied unchanged to the corresponding test matrix. Subject- or donor-level grouping was retained through constrain where identifiers were available; otherwise, the fixed split is interpreted as a computational benchmark rather than an estimate of independent-subject generalization.")

dataset_body = [
    ["TCGA-HNSC methylation", "Classification", "520", "58", "782", "2"],
    ["CCLE", "Classification", "547", "71", "1,000", "18"],
    ["TCGA-BRCA", "Classification", "756", "88", "1,000", "5"],
    ["MetRef", "Classification", "773", "100", "375", "22"],
    ["TCGA Pan-Cancer", "Classification", "3,000", "982", "850", "32"],
    ["GTEx v8", "Classification", "3,000", "797", "1,000", "32"],
    ["Retina", "Classification", "22,402", "22,406", "50", "12"],
    ["Tabula Muris", "Classification", "50,043", "50,059", "50", "32"],
    ["CIFAR-100", "Classification", "50,000", "10,000", "768", "100"],
    ["CBMC CITE-seq", "Regression", "7,755", "862", "1,000", "10"],
    ["PRISM", "Regression", "479", "54", "1,000", "4,686"],
    ["NMR", "Regression", "1,200", "321", "13,000", "28,355"],
]
add_table(supp, "Table S1. Prepared benchmark dimensions.",
          ["Dataset", "Task", "Training n", "Test n", "p", "q"], dataset_body, 6.8)

acquisition_body = [
    ["MetRef", "KODAMA package data; zero columns removed, then normalization and scaling", "Acquisition script; object not redistributed"],
    ["CIFAR-100", "University of Toronto public archive; stored feature representation", "Download/preparation script"],
    ["CBMC CITE-seq", "GEO GSE100866", "Download/preparation script"],
    ["Retina", "GEO GSE63472; 50-dimensional prepared representation", "Download/preparation script"],
    ["Tabula Muris", "Bioconductor ExperimentHub resource", "Bioconductor acquisition script"],
    ["CCLE, GTEx, TCGA, PRISM", "Public project resources subject to source terms", "Acquisition and harmonization scripts"],
    ["NMR", "Study-specific prepared matrices associated with Vignoli et al. [9]", "Access subject to original study conditions"],
    ["ImageNet/DINOv2", "Derived representation; no image files redistributed", "Current stress-test runner and manifest"],
]
add_table(supp, "Table S2. Data acquisition and redistribution status.",
          ["Dataset", "Source/preparation", "Distributed material"], acquisition_body, 6.8)

heading(supp, "S2. Algorithmic complexity and backend residency")
complexity_body = [
    ["PLS-SVD, explicit", "Form XᵀY: O(npq); rSVD passes over the p by q operator: O(pql) per pass", "O(pq + (p+q)l + nA)", "CPU; CUDA float32/64; Metal float32"],
    ["PLS-SVD, implicit", "Each operator pass applies Xᵀ(YΩ) and Yᵀ(XQ): O(n(p+q)l)", "O((n+p+q)l + nA); no p by q S", "Route selected by shape and backend"],
    ["SIMPLS", "Sequential direction refreshes and A rank-one deflations; matrix-matrix refresh cost depends on block width", "O(pq + (n+2p+q)A + n² when the sample-space response Gram is cached)", "CPU; CUDA float32/64; Metal float32"],
    ["OPLS", "north orthogonal filters, followed by the selected predictive PLS core", "Predictive-core storage plus O((n+p)north)", "CPU; CUDA float32/64; Metal float32"],
    ["Kernel PLS, linear", "Linear shortcut", "As selected linear core", "CPU/CUDA/Metal according to core"],
    ["Kernel PLS, nonlinear", "Kernel construction O(n²p), double centering and sample-space SIMPLS", "O(n² + nA + qA) Gram/workspace storage", "CPU; CUDA float32/64; Metal float32"],
    ["Compact prediction", "XnewR and latent response mapping", "O(ntest A + (p+q)A)", "Supported CPU/CUDA/Metal routes"],
]
add_table(supp, "Table S3. Dominant operations, storage and residency.",
          ["Route", "Dominant work", "Additional storage", "Residency"], complexity_body, 6.5)
paragraph(supp, "Here A is the maximum retained component count and l is the randomized sketch width. Explicit means that the p by q cross-covariance is stored. Implicit means that only its action on a narrow matrix is evaluated, so S is not stored.")

add_table(supp, "Algorithm S1. OPLS execution used by fastPLS.",
          ["Step", "Operation"], [
    ["1", "Apply training centering or scaling to X and center Y; set the filtered predictor matrix Xf = X."],
    ["2", "For each requested orthogonal component, form S = XfᵀY and obtain its leading predictive direction w with the active randomized solver."],
    ["3", "Form t = Xf w and p = Xfᵀt/(tᵀt). Construct the response-orthogonal direction wo = p - w(wᵀp)/(wᵀw), then normalize wo."],
    ["4", "Form to = Xf wo and po = Xfᵀto/(toᵀto); update Xf <- Xf - to poᵀ and retain wo and po for prediction."],
    ["5", "Fit the accelerated SIMPLS core to Xf and Y, retaining compact predictive factors for every requested prefix."],
    ["6", "For a new matrix, apply the training preprocessing and each stored orthogonal filter before the predictive projection; equivalently map the compact rotations through the accumulated filters."],
], 7.2)

add_table(supp, "Algorithm S2. Linear and nonlinear kernel-PLS execution.",
          ["Step", "Operation"], [
    ["1", "Apply training centering or scaling to X. For a linear kernel, dispatch directly to the linear SIMPLS core and do not materialize a Gram matrix."],
    ["2", "For a radial-basis or polynomial kernel, verify that the n by n training Gram matrix and workspaces fit the guarded memory budget; otherwise stop before allocation."],
    ["3", "Construct Kij = exp(-gamma ||xi-xj||²) for the radial-basis kernel or Kij = (gamma xiᵀxj + coef0)^degree for the polynomial kernel."],
    ["4", "Double-center K using its training row means, column means and grand mean, then fit the accelerated SIMPLS core to the centered sample-space matrix and Y."],
    ["5", "For Xnew, apply training preprocessing, construct the test-by-training cross-kernel, and center it with the stored training means, each test-row mean and the training grand mean."],
    ["6", "Project the centered cross-kernel through the compact kernel-space factors and restore the training-response mean."],
], 7.2)

heading(supp, "S3. Numerical validation and implementation ablation")
exact_prefixes = sum(int(number(r["component_prefixes"])) for r in exact_validation)
exact_failures = sum(int(number(r["convergence_failures"])) for r in exact_validation)
exact_prediction_error = max(number(r["max_prediction_relative_error"])
                             for r in exact_validation)
exact_label_values = [number(r["min_classification_label_agreement"])
                      for r in exact_validation
                      if math.isfinite(number(r["min_classification_label_agreement"]))]
validation_body = [[
    "SIMPLS component-wise dense reference", str(exact_prefixes), str(exact_failures),
    fmt(exact_prediction_error, 6), "NA",
    fmt(min(exact_label_values), 4) if exact_label_values else "NA",
    "Exact-reference cases; includes near-tied singular values",
]]
for r in rsvd_validation:
    validation_body.append([
        f"rSVD qualification, {display_backend(r['backend'])}",
        r["comparisons"],
        str(int(number(r["comparisons"])) - int(number(r["comparisons_within_tolerance"]))),
        fmt(r["max_prediction_relative_error"], 6),
        fmt(r["min_prediction_correlation"], 6),
        fmt(r["min_label_agreement"], 4),
        f"Profiles {r['control_profiles']}; controls {r['effective_controls']}",
    ])
for r in family_validation:
    validation_body.append([
        display_family(r["family"]), r["runs"], r["failures"],
        fmt(r["max_prediction_relative_error"], 6),
        fmt(r["min_prediction_correlation"], 6),
        fmt(r["min_label_agreement"], 4),
        "Deterministic float64 CPU estimator check",
    ])
add_table(supp, "Table S4. Consolidated numerical-validation summary.",
          ["Evidence", "Comparisons", "Failures", "Maximum prediction error", "Minimum correlation", "Minimum label agreement", "Scope"],
          validation_body, 5.8)
paragraph(supp, "The component-wise SIMPLS validation compares the optimized deterministic execution with a dense reference on well-conditioned, collinear, rank-deficient, high-response, p<n, p>n and near-tied cases. rSVD qualification uses route-specific profiles and predefined numerical tolerances; meeting these tolerances is not described as exact equality. Prefix-level errors and all replicate records remain in the benchmark archive.")

ablation_body = []
for optimization in sorted({r["optimization"] for r in ablation}):
    current = [r for r in ablation
               if r["optimization"] == optimization and r["optimization_applicable"] == "TRUE"]
    if not current:
        continue
    speedups = [number(r["speedup"]) for r in current]
    rss = [number(r["rss_reduction_pct"]) for r in current]
    differences = [number(r["metric_abs_diff"]) for r in current]
    agreements = [number(r["prediction_agreement_min"]) for r in current]
    ablation_body.append([
        optimization.replace("_", " "), str(len(current)),
        f"{min(speedups):.2f}–{max(speedups):.2f}",
        f"{min(rss):.1f}–{max(rss):.1f}",
        fmt(max(differences), 6), fmt(min(agreements), 4),
    ])
add_table(supp, "Table S5. Same-code multidataset SIMPLS ablation.",
          ["Optimization", "Applicable datasets", "Speed-up range", "RSS reduction range (%)", "Maximum metric difference", "Minimum prediction agreement"],
          ablation_body, 6.0)
paragraph(supp, "A speed-up above one favours the optimized state. Negative RSS reduction indicates a larger measured complete-process increment. Individual optimizations are shape dependent and are therefore combined by the public dispatcher rather than claimed to accelerate every matrix regime.")

software_capability_body = [
    ["fastPLS", "Compiled C++/linked BLAS", "Yes; verified OpenBLAS build", "CUDA", "Metal", "float32/float64, route-specific"],
    ["IKPLS", "NumPy or JAX", "Runtime dependent", "JAX-compatible", "Not evaluated", "float32/float64, runtime dependent"],
    ["nirs4all-methods", "Compiled C++ through pls4all", "Linked BLAS/runtime dependent", "Not evaluated", "Not evaluated", "float64 in tested Python binding"],
    ["scikit-learn", "NumPy/SciPy", "Linked BLAS/runtime dependent", "No native PLS route", "No native PLS route", "float64 in tested route"],
    ["pls", "R/compiled numerical libraries", "Linked BLAS only", "No", "No", "R numeric float64"],
    ["plsgenomics", "R/compiled dependencies", "No package-level control", "No", "No", "R numeric float64"],
    ["mdatools", "R/compiled dependencies", "No package-level control", "No", "No", "R numeric float64"],
    ["plsdepot", "R", "No package-level control", "No", "No", "R numeric float64"],
    ["pcv", "R/compiled dependencies", "No package-level control", "No", "No", "R numeric float64"],
    ["chemometrics", "R/compiled dependencies", "No package-level control", "No", "No", "R numeric float64"],
    ["mixOmics", "R/compiled dependencies", "Linked BLAS only", "No", "No", "R numeric float64"],
    ["spls", "R/compiled dependencies", "No package-level control", "No", "No", "R numeric float64"],
]
add_table(supp, "Table S6. Computational capabilities of compared implementations.",
          ["Implementation", "CPU route", "Multiple CPU threads", "NVIDIA GPU", "Apple GPU", "Precision"],
          software_capability_body, 5.8)

heading(supp, "S4. Complete CPU and accelerator results")
backend_family_names = {
    "plssvd": "PLS-SVD", "simpls": "SIMPLS",
    "opls": "OPLS", "kernelpls": "kernel PLS",
}
backend_body = []
backend_memory_body = []
for r in fig2:
    backend_body.append([
        r["platform"], r["dataset"],
        backend_family_names.get(r["method"], r["method"]), r["ncomp"],
        fmt(r["cpu_time_sec"], 3), fmt(r["accelerator_time_sec"], 3),
        fmt(r["ratio"], 2), fmt(r["cpu_metric"], 4),
        fmt(r["accelerator_metric"], 4), r["rsvd_controls"],
        display_route(r["execution_route"]),
    ])
    backend_memory_body.append([
        r["platform"], r["dataset"],
        backend_family_names.get(r["method"], r["method"]), r["ncomp"],
        fmt(r["cpu_incremental_rss_mib"], 1),
        fmt(r["accelerator_incremental_rss_mib"], 1),
        fmt(r["memory_ratio"], 2), fmt(r.get("accelerator_gpu_peak_mib"), 1),
        display_route(r["execution_route"]),
    ])
add_table(supp, "Table S7. Complete selected-point CPU/CUDA and fixed CPU/Metal operation-split comparison.",
          ["Platform", "Dataset", "Family", "A", "CPU s", "Accelerator s", "Time ratio", "CPU metric", "Accelerator metric", "rSVD controls", "Route"], backend_body, 5.3)
add_table(supp, "Table S8. Selected-point host- and device-memory comparison.",
          ["Platform", "Dataset", "Family", "A", "CPU RSS MiB", "Accelerator RSS MiB", "RSS ratio", "GPU peak MiB", "Route"], backend_memory_body, 5.4)
paragraph(supp, "The metric is accuracy for classification and RMSD for regression. CPU/accelerator time ratios above one favour the accelerator. Every row is measured in a fresh process and includes device and pipeline initialization. Metal rows were recalculated with fastPLS 0.99.42; the retained Linux CPU/CUDA rows use 0.99.41, whose corresponding CPU and CUDA numerical paths are unchanged in 0.99.42. The Metal rows use one invariant mathematical partition: Metal evaluates fitting products involving the training sample matrix, while the CPU performs reduced factorizations, sequential PLS updates, LDA and compact prediction. Host RSS is baseline-corrected complete-process memory. GPU peak is the sampled process allocation and can include CUDA context, library and allocator state; it is not isolated algorithmic workspace. Values are paired within workstation, and no timing is suppressed on the basis of metric disagreement.")

precision_body = [[
    r["dataset"], display_family(r["method"]),
    display_backend(r["backend"]), r["precision"],
    r.get("ncomp_requested", r.get("ncomp", "")),
    r.get("ncomp_effective", r.get("ncomp", "")),
    r["repetitions"], fmt(r["median_total_sec"], 3),
    f"{fmt(r['q1_total_sec'], 3)}-{fmt(r['q3_total_sec'], 3)}",
    r["metric_name"], fmt(r["median_metric"], 6),
    fmt(r["median_incremental_peak_rss_mib"], 1),
] for r in precision]
add_table(supp, "Table S9. Matched float32 and float64 runtime, prediction and memory.",
          ["Dataset", "Family", "Backend", "Precision", "Requested A",
           "Effective A", "Runs",
           "Median s", "IQR s", "Metric", "Value", "RSS increment MiB"],
          precision_body, 5.5)
paragraph(supp, "Conversion to float32 was completed before the timed fit and before the pre-fit RSS baseline. Metal appears only in float32 because the tested Apple GPU does not provide the float64 arithmetic required by the operation-split implementation. CUDA RSS increments can include context and allocator initialization and are therefore complete-process increments, not isolated algorithmic workspace.")

solver_body = [[
    r["shape"], display_family(r["family"]), r["solver"],
    r["ncomp"], r["repetitions"],
    fmt(r["median_total_sec"], 3),
    f"{fmt(r['q1_total_sec'], 3)}-{fmt(r['q3_total_sec'], 3)}",
    fmt(r["median_metric"], 7),
    fmt(r["median_incremental_peak_rss_mib"], 1),
] for r in solver]
add_table(supp, "Table S10. Native rSVD versus the IRLBA companion under matched outputs.",
          ["Shape", "Family", "Solver", "A", "Runs", "Median s", "IQR s",
           "RMSD", "RSS increment MiB"], solver_body, 5.8)
paragraph(supp, "The matrices, preprocessing, 20-component workload, model family and held-out prediction output were identical within each pair. IRLBA is retained only in the GPL companion benchmark package; it is not a public fastPLS solver. The comparison therefore isolates low-rank solver choice within the same surrounding PLS implementation.")

heading(supp, "S5. Component paths across benchmark datasets")
dataset_names = {
    "cbmc_citeseq": "CBMC CITE-seq", "ccle": "CCLE",
    "cifar100": "CIFAR-100", "gtex_v8": "GTEx v8", "metref": "MetRef",
    "prism": "PRISM", "retina": "Retina", "tabula": "Tabula Muris",
    "tcga_brca": "TCGA-BRCA",
    "tcga_hnsc_methylation": "TCGA-HNSC methylation",
    "tcga_pan_cancer": "TCGA Pan-Cancer",
    "nmr": "NMR", "imagenet": "ImageNet/DINOv2",
}
family_names = {
    "plssvd": "PLS-SVD", "simpls": "SIMPLS",
    "opls": "OPLS", "kernelpls": "kernel PLS",
}
component_selection_body = [[
    dataset_names.get(r["dataset"], r["dataset"]),
    r["plssvd_ncomp"], r["simpls_ncomp"], r["external_ncomp"],
    r["task_type"], r["include_external"],
] for r in figure1_contract]
add_table(supp, "Table S11. Component counts used in the current benchmark panel.",
          ["Dataset", "PLS-SVD A", "SIMPLS A", "External A", "Task", "External status"],
          component_selection_body, 6.4)
paragraph(supp, "Except for the explicitly fixed 1,000-component ImageNet stress point, component counts were fixed before the current timing rerun by ten-fold cross-validation performed only within each training set, using seed 123 and the ascending integer grids documented with the component-path results. Classification selected the SIMPLS-LDA component count with the largest cross-validated accuracy; regression selected the SIMPLS component count with the smallest cross-validated RMSD. The first value on the ascending grid was retained when metrics tied. These values are the best retained settings within the evaluated grids, not unconstrained optima. The Figure 1 component count was shared by fastPLS and each applicable independent implementation.")

correlation_body = [[
    r["platform"], dataset_names.get(r["dataset"], r["dataset"]),
    family_names.get(r["method"], r["method"]),
    display_backend(r["backend"]),
    r["n_path_points"], fmt(r["rho_metric"], 3),
    fmt(r["rho_total_time"], 3), fmt(r["rho_incremental_rss"], 3),
] for r in component_correlations]
add_table(supp, "Table S12. Spearman associations with requested component count.",
          ["Computer", "Dataset", "Family", "Backend", "Path points", "Metric rho", "Time rho", "RSS rho"],
          correlation_body, 5.2)
paragraph(supp, "Positive time or RSS correlations indicate increasing computational cost with additional components. The sign of the predictive-metric correlation is interpreted according to the endpoint: larger accuracy is better, whereas smaller RMSD is better. The complete per-component medians, interquartile ranges, controls and execution routes accompany the source files.")

component_figure_order = [
    "ccle", "cifar100", "gtex_v8", "metref", "retina", "tabula",
    "tcga_brca", "tcga_hnsc_methylation", "tcga_pan_cancer",
    "cbmc_citeseq", "prism",
]
for figure_index, dataset_id in enumerate(component_figure_order, start=1):
    add_figure(
        supp,
        f"component_path_{dataset_id}.png",
        f"Figure S{figure_index}. {dataset_names[dataset_id]} component paths. Predictive metric, total fitting-plus-prediction time and incremental host RSS are shown for PLS-SVD, SIMPLS, OPLS and kernel PLS on the current CPU and available accelerator routes; dotted vertical lines mark the training-selected component count for each family.",
        6.45,
    )

heading(supp, "S6. NMR component selection and fixed-component comparison")
selection_body = [[
    family_names.get(r["family"], r["family"]),
    r["selected_ncomp"], r["minimum_mean_ncomp"],
    fmt(r["one_se_threshold"], 7), r["eligible_ncomp"].replace(",", ", "),
    r["largest_tested_ncomp"], r["n_splits_successful"],
] for r in nmr_decision]
add_table(supp, "Table S13. NMR one-standard-error component decisions.",
          ["Family", "Selected A", "Mean-minimum A", "One-SE threshold", "Eligible A", "Grid maximum", "Successful splits"], selection_body, 6.8)
add_figure(supp, "figureS1_nmr_component_selection.png", "Figure S12. Training-only NMR component selection. Lines show mean validation RMSD across five paired splits; error bars show standard errors. The selected value is the smallest component count within one standard error of the minimum mean RMSD.", 6.45)

nmr_body = [[
    r["implementation"], r["workstation"], r["precision"], r["ncomp"],
    fmt(r["total_time_sec"], 3), fmt(r["RMSD"], 7), fmt(r["Q2"], 4),
    fmt(r["incremental_rss_mib"], 1), fmt(r["incremental_gpu_mib"], 1),
] for r in fig3]
add_table(supp, "Table S14. NMR fixed 165-component implementation comparison.",
          ["Implementation", "Workstation", "Precision", "A", "Total s", "RMSD", "Q²", "RSS increment MiB", "GPU increment MiB"], nmr_body, 5.8)
paragraph(supp, "The fixed 165-component analysis compares the current PLS-SVD and SIMPLS implementations under a common workload. CPU and CUDA rows are paired on the Intel/NVIDIA workstation. Metal rows were measured on the Apple M3 and are reported separately rather than treated as direct speed ratios to the Linux CPU. Each summary uses three isolated processes; input conversion is excluded and accelerator initialization and transfer are included.")

add_figure(supp, "figureS_precision_float32_float64.png",
           "Figure S13. Matched float32 and float64 evidence. Runtime ratios above one favour float32; incremental-RSS ratios below one favour float32; accuracy differences near zero indicate numerical agreement. PLS-SVD, SIMPLS, OPLS and radial-basis kernel PLS were evaluated on MetRef and GTEx v8. Conversion time is excluded. Metal is reported in Table S9 in its supported float32 precision only.", 6.45)
add_figure(supp, "figureS_rsvd_vs_irlba.png",
           "Figure S14. Matched rSVD-versus-IRLBA comparison. Runtime values above one favour rSVD. Incremental-RSS ratios below one favour rSVD. Each bar summarizes five isolated processes.", 6.45)

heading(supp, "S7. Verified CPU thread scaling")
multicore_body = [[
    r["workload"], r["active_openblas_threads"], r["n_train"], r["n_test"],
    r["p"], r["q"], r["ncomp"], r["repetitions"], fmt(r["median_sec"], 3),
    f"{fmt(r['q1_sec'], 3)}–{fmt(r['q3_sec'], 3)}", fmt(r["speedup"], 2),
    r["metric_name"], fmt(r["metric_value"], 6), r["prediction_agreement"],
] for r in multicore]
add_table(supp, "Table S15. Verified OpenBLAS thread-scaling benchmark.",
          ["Workload", "Threads", "Train n", "Test n", "p", "q", "A", "Runs", "Median s", "IQR s", "Speed-up", "Metric", "Value", "Same predictions"],
          multicore_body, 5.2)
add_figure(supp, "figureS_multicore_scaling.png", "Figure S15. Verified CPU thread scaling. Speed-up is relative to the median one-thread time for each controlled workload. The OpenBLAS thread count was probed directly before each fit, and predictions were identical across settings.", 6.45)

heading(supp, "S8. Precision and capability interpretation")
capability_body = [
    ["SIMPLS", "CPU", "float64/float32", "Compiled", "Validated public path"],
    ["SIMPLS", "CUDA", "float64/float32", "Device-native after input transfer", "CUDA availability required"],
    ["SIMPLS", "Metal", "float32", "Metal sample products; CPU reduced SVD, sequential updates, LDA and prediction", "Fixed operation split; float64 returns an error"],
    ["PLS-SVD", "CPU", "float64/float32", "Compiled", "Validated public path"],
    ["PLS-SVD", "CUDA", "float64/float32", "Device-native after input transfer", "CUDA availability required"],
    ["PLS-SVD", "Metal", "float32", "Metal cross-products; CPU reduced QR/SVD and compact prediction", "Fixed operation split; float64 returns an error"],
    ["OPLS", "CPU", "float64/float32", "Compiled", "Supported"],
    ["OPLS", "CUDA", "float64/float32", "Device-native filtering and predictive core", "CUDA availability required"],
    ["OPLS", "Metal", "float32", "Metal sample products; CPU orthogonal filtering, predictive updates and prediction", "Fixed operation split; float64 returns an error"],
    ["Kernel PLS, linear", "CPU/CUDA", "float64/float32", "Uses the selected linear core", "Supported according to core"],
    ["Kernel PLS, linear", "Metal", "float32", "Uses the fixed CPU/Metal split of the linear core", "float64 returns an error"],
    ["Kernel PLS, nonlinear", "CUDA", "float64/float32", "Device-native Gram construction, centering and fit", "O(n²) device storage guard"],
    ["Kernel PLS, nonlinear", "Metal", "float32", "Metal Gram/sample products; CPU reduced decomposition and sequential updates", "Fixed operation split; O(n²) unified-memory guard"],
    ["LDA", "CPU", "float64/float32", "Compiled covariance and Cholesky", "Supported"],
    ["LDA", "CUDA", "float64/float32", "Device-native score, covariance, Cholesky and prediction", "Supported"],
    ["LDA", "Metal", "float32", "CPU score-space covariance, Cholesky and prediction", "Part of the fixed operation split; float64 unavailable"],
]
add_table(supp, "Table S16. Public precision and backend capability matrix.",
          ["Family/head", "Backend", "Precision", "Residency", "Status"], capability_body, 6.5)
paragraph(supp, "float32 support means that the principal supported numerical buffers use single precision. It does not imply that every R bookkeeping object or complete-process allocation is half the corresponding float64 measurement. Metal is an operation-level CPU/GPU implementation, not a whole-model shape dispatcher: the same operations are assigned to Metal and CPU for every dataset. An unsupported backend or precision combination raises an informative error before fitting; no CPU fallback is used.")

heading(supp, "S9. Independent implementations")
ikpls_body = []
for r in ikpls_all:
    status = "Completed" if r["status"] == "success" else "Failed: memory"
    ikpls_body.append([
        "IKPLS", dataset_names.get(r["dataset"], r["dataset"]),
        r["task_type"], "float32", r["ncomp"], r["metric_name"],
        fmt(r["metric_value"], 5), fmt(r["top5_accuracy"], 4),
        fmt(r["median_total_sec"], 3), fmt(r["iqr_total_sec"], 3),
        fmt(r["peak_rss_mib"], 0), r["repetitions"], status,
    ])
python_success_keys = set()
for r in python_panel:
    python_success_keys.add((r["dataset"], r["implementation"]))
    is_classification = r["task_type"] == "classification"
    warning_runs = int(number(r.get("runs_with_warnings", 0)))
    status = "Completed"
    if warning_runs:
        status += f"; warnings in {warning_runs} run(s)"
    input_precision = r.get("input_precision") or r.get("precision") or "NA"
    model_precision = r.get("model_precision") or r.get("precision") or "NA"
    precision = (
        input_precision
        if input_precision == model_precision
        else f"{input_precision} / {model_precision}"
    )
    ikpls_body.append([
        r["algorithm"], dataset_names.get(r["dataset"], r["dataset"]),
        r["task_type"], precision, r["ncomp"],
        "Accuracy" if is_classification else "RMSD",
        fmt(r["accuracy"] if is_classification else r["rmsd"], 5),
        fmt(r["top5_accuracy"], 4), fmt(r["median_total_sec"], 3),
        fmt(r["iqr_total_sec"], 3), fmt(r["median_peak_rss_mib"], 0),
        r["repetitions"], status,
    ])
ikpls_meta = {r["dataset"]: r for r in ikpls_all}
for r in python_large:
    label = r.get("algorithm") or python_labels.get(
        r.get("implementation", ""), r.get("implementation", "Python PLS")
    )
    meta = ikpls_meta.get(r.get("dataset", ""), {})
    if r.get("status") == "success":
        is_classification = r.get("task_type") == "classification"
        warning_runs = int(number(r.get("warning_count", 0)))
        status = "Completed; single-run feasibility"
        if warning_runs:
            status += "; numerical warning"
        ikpls_body.append([
            label, dataset_names.get(r["dataset"], r["dataset"]),
            r["task_type"], r["precision"], r["ncomp"],
            "Accuracy" if is_classification else "RMSD",
            fmt(r["accuracy"] if is_classification else r["rmsd"], 5),
            fmt(r.get("top5_accuracy"), 4), fmt(r["total_sec"], 3),
            "NA", fmt(r["peak_rss_mib"], 0), "1", status,
        ])
    else:
        ikpls_body.append([
            label, dataset_names.get(r.get("dataset", ""), r.get("dataset", "")),
            r.get("task_type") or meta.get("task_type", "regression"),
            r.get("precision") or "float64", r.get("ncomp", "NA"), "NA", "NA",
            "NA", "NA", "NA", "NA", "1",
            "Failed: " + r.get("error", "native worker failure")[:140],
        ])
python_failure_priority = {
    "timeout": 4,
    "failed": 3,
    "not_repeated_after_failure": 2,
    "not_repeated_long_runtime": 1,
}
python_failures = {}
for r in python_status:
    key = (r.get("dataset", ""), r.get("implementation", ""))
    if key in python_success_keys or r.get("status") == "success":
        continue
    current = python_failures.get(key)
    current_priority = python_failure_priority.get(
        current.get("status", "") if current else "", 0
    )
    candidate_priority = python_failure_priority.get(r.get("status", ""), 0)
    if current is None or candidate_priority > current_priority:
        python_failures[key] = r
for key, r in sorted(python_failures.items()):
    meta = ikpls_meta.get(r.get("dataset", ""), {})
    label = python_labels.get(
        r.get("implementation", ""), r.get("implementation", "")
    )
    ikpls_body.append([
        label, dataset_names.get(r.get("dataset", ""), r.get("dataset", "")),
        meta.get("task_type", "NA"), "float32 / float64", meta.get("ncomp", "NA"), "NA", "NA",
        "NA", "NA", "NA", "NA", r.get("runs", "NA"),
        r.get("status", "Failed").replace("_", " ").capitalize() + ": " +
        r.get("detail", "native worker failure")[:140],
    ])
paragraph(supp, "In Figure 1, all implementations were measured on the same Ubuntu 22.04 workstation with an Intel Core i7-13700 processor and 32 GiB RAM. fastPLS 0.99.65 was linked directly to OpenBLAS 0.3.29 and used SIMPLS, backend = 'cpu', scaling = 'centering', fit = FALSE, proj = FALSE and return_variance = FALSE with float32 predictors, oversampling 32, five power iterations and seed 123. Classification used latent-score LDA; regression used continuous prediction and RMSD. Component counts followed Table S11 and were shared across applicable implementations. IKPLS used its improved-kernel formulation in float32. Remaining Python results used the recorded precision. All ordinary tasks used one effective CPU thread and identical inputs and train/test splits. ImageNet/DINOv2 used 1,000,000 training and 281,167 held-out embeddings with 1,000 requested components; only previously feasible methods were evaluated at this scale.")
add_table(supp, "Table S17. Independent Python PLS results across the benchmark datasets.",
          ["Implementation", "Dataset", "Task", "Input / model", "A", "Metric", "Value", "Top-5", "Median s", "IQR s", "Peak RSS MiB", "Runs", "Status"],
          ikpls_body, 5.2)
paragraph(supp, "ImageNet and NMR remain single-run feasibility tests. Failures and convergence warnings are retained rather than excluded. IKPLS failed on 50-component NMR because its coefficient path required a 68.7-GiB float32 tensor on the 32-GiB workstation.")

heading(supp, "S10. ImageNet stress test")
if has_imagenet:
    image_body = [[r.get("classifier", ""), r.get("ncomp_requested", ""),
                   fmt(r.get("top1_accuracy"), 4), fmt(r.get("top5_accuracy"), 4),
                   fmt(r.get("total_time_sec"), 2),
                   fmt(r.get("host_observed_mb"), 0),
                   fmt(r.get("gpu_after_top5_mb"), 0), r.get("fit_residency", "")]
                  for r in image]
    add_table(supp, "Table S18. Current-release ImageNet/DINOv2 float32 SIMPLS stress test.",
              ["Head", "A", "Top-1", "Top-5", "Total s", "Observed RSS MiB", "GPU allocation MiB", "Route"], image_body, 6.5)
else:
    paragraph(supp, "The current-release ImageNet calculation has not completed. Earlier package-version and hybrid results are intentionally excluded from this document.")

heading(supp, "S11. Reproducibility and software checks")
paragraph(
    supp,
    "The Basic Linear Algebra Subprograms (BLAS) define standard dense "
    "matrix operations but do not identify a specific vendor library. "
    "fastPLS is linked at compilation to one CPU BLAS/LAPACK implementation. "
    "Apple Accelerate is the default optimized implementation on macOS, "
    "whereas OpenBLAS is used for the authors' Linux and Windows performance "
    "builds. If OpenBLAS is unavailable, installation remains possible using "
    "the BLAS/LAPACK libraries supplied with R. These implementations can "
    "differ substantially in latency and thread scaling, so the linked "
    "library and active thread count must be reported with CPU benchmarks. "
    "The fastPLS_blas() function returns the library selected at compilation. "
    "Apple Accelerate is a CPU numerical framework and is distinct from the "
    "package's Metal CPU/GPU backend."
)
repro_body = [
    ["Package", "fastPLS 0.99.65 source candidate", "Current Figure 1, manuscript, vignette and manual; other analysis versions are identified in their corresponding tables"],
    ["macOS", "Apple M3, 8 CPU cores, 8 GB unified memory", "CPU and Metal; R CMD check tests and Metal integration"],
    ["CUDA workstation", "Intel Core i7-13700; 32 GB RAM; NVIDIA GeForce RTX 5060 Ti, 16 GB", "CPU and CUDA benchmark panels"],
    ["Apple Accelerate", "macOS system BLAS/LAPACK framework", "Default macOS CPU library; separate from Metal execution"],
    ["OpenBLAS", "Optimized open-source BLAS/LAPACK implementation", "Required for the reported Linux and Windows CPU performance builds"],
    ["R BLAS/LAPACK", "Libraries supplied by the active R installation", "Portable fallback when OpenBLAS is unavailable; not treated as a matched performance baseline"],
    ["R package checks", "R CMD check", "Tests, examples, documentation and vignette completed locally"],
    ["Bioconductor checks", "BiocCheck", "0 errors; remaining style and repository-status notes are not numerical failures"],
]
add_table(supp, "Table S19. Reproducibility, platform and CPU numerical-library summary.",
          ["Item", "Configuration", "Role/status"], repro_body, 6.8)
paragraph(supp, "Benchmark scripts record requested method, component count, precision, seed, rSVD controls, executed route, timing, metrics and completion status. CUDA timing includes transfer and synchronization in the public workflow. Metal float64 is tested as an informative error, not as a CPU fallback.")

main_path = OUT / "fastPLS_manuscript_0.99.65_current.docx"
supp_path = OUT / "fastPLS_supplement_0.99.65_current.docx"
main.save(main_path)
supp.save(supp_path)
print(main_path)
print(supp_path)
print(f"ImageNet current results included: {has_imagenet}")
