// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// extra_pls_cpp
Rcpp::List extra_pls_cpp(const arma::mat& x, const arma::mat& y, arma::ivec components, std::string method, int scaling, bool fitted);
RcppExport SEXP _fastPLSextra_extra_pls_cpp(SEXP xSEXP, SEXP ySEXP, SEXP componentsSEXP, SEXP methodSEXP, SEXP scalingSEXP, SEXP fittedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fitted(fittedSEXP);
    rcpp_result_gen = Rcpp::wrap(extra_pls_cpp(x, y, components, method, scaling, fitted));
    return rcpp_result_gen;
END_RCPP
}
// extra_predict_cpp
Rcpp::List extra_predict_cpp(Rcpp::List model, const arma::mat& x);
RcppExport SEXP _fastPLSextra_extra_predict_cpp(SEXP modelSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(extra_predict_cpp(model, x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastPLSextra_extra_pls_cpp", (DL_FUNC) &_fastPLSextra_extra_pls_cpp, 6},
    {"_fastPLSextra_extra_predict_cpp", (DL_FUNC) &_fastPLSextra_extra_predict_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastPLSextra(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
