# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extra_pls_cpp <- function(x, y, components, method, scaling, fitted) {
    .Call(`_fastPLSextra_extra_pls_cpp`, x, y, components, method, scaling, fitted)
}

extra_predict_cpp <- function(model, x) {
    .Call(`_fastPLSextra_extra_predict_cpp`, model, x)
}
